from header_common import *
from header_operations import *
from header_parties import *
from header_items import *
from header_skills import *
from header_triggers import *
from header_troops import *
from header_music import *

from module_constants import *

####################################################################################################################
# Simple triggers are the alternative to old style triggers. They do not preserve state, and thus simpler to maintain.
#
#  Each simple trigger contains the following fields:
# 1) Check interval: How frequently this trigger will be checked
# 2) Operation block: This must be a valid operation block. See header_operations.py for reference. 
####################################################################################################################



simple_triggers = [
	(6.0,
		[
			(try_for_range, ":faction", "fac_kingdom_1", "fac_undeads"),
				(faction_get_slot, ":faction_28", ":faction", 28),
				(le, ":faction_28", 0),
				(faction_set_slot, ":faction", slot_faction_state, 1),
			(try_end),
			(call_script, "script_temp_save_number11_initialize"),
			(try_for_range, ":party", "p_pyongyang", "p_place_end"),
				(store_faction_of_party, ":faction_of_party_party", ":party"),
				(faction_slot_eq, ":faction_of_party_party", slot_faction_player_alarm, 1),
				(faction_slot_eq, ":faction_of_party_party", slot_faction_state, 1),
				(party_get_battle_opponent, ":battle_opponent_party", ":party"),
				(try_begin),
					(lt, ":battle_opponent_party", 0),
				(else_try),
					(faction_set_slot, ":faction_of_party_party", slot_faction_state, ":party"),
					(try_begin),
						(ge, ":faction_of_party_party", "fac_kingdom_1"),
						(this_or_next|eq, ":faction_of_party_party", "$contract_fac"),
						(eq, ":faction_of_party_party", "$wm_player_fac"),
						(str_store_party_name, 1, ":party"),
						(display_message, "str_under_attackk", 0x00ffff00),
						(party_relocate_near_party, "p_defence_target", ":party", 0),
						(party_set_flags, "p_defence_target", 256, 0),
						(party_set_icon, "p_defence_target", "icon_defence_target"),
					(try_end),
				(try_end),
			(try_end),
			(assign, ":value", "$wm_player_fac"),
			(try_begin),
				(gt, "$contract_time", 0),
				(is_between, "$contract_fac", "fac_kingdom_1", "fac_kingdoms_end"),
				(neg|troop_slot_ge, "trp_player", 18, 11),
				(assign, ":value", "$contract_fac"),
			(try_end),
			(try_begin),
				(is_between, ":value", "fac_kingdom_1", "fac_kingdoms_end"),
				(faction_get_slot, ":wm_player_fac_state", "$wm_player_fac", slot_faction_state),
				(neg|is_between, ":wm_player_fac_state", "p_pyongyang", "p_place_end"),
				(party_set_flags, "p_defence_target", 256, 1),
			(try_end),
			(try_begin),
				(is_between, ":value", "fac_kingdom_1", "fac_kingdoms_end"),
				(faction_get_slot, ":wm_player_fac_number_of_parties", "$wm_player_fac", slot_faction_number_of_parties),
				(neg|is_between, ":wm_player_fac_number_of_parties", "p_pyongyang", "p_place_end"),
				(party_set_flags, "p_attack_target", 256, 1),
			(try_end),
			(try_begin),
				(neg|is_between, ":value", "fac_kingdom_1", "fac_kingdoms_end"),
				(party_set_flags, "p_defence_target", 256, 1),
				(party_set_flags, "p_attack_target", 256, 1),
			(try_end),
			(try_begin),
				(gt, "$player_recruit_train_start", 0),
				(neg|map_free),
				(is_between, "$g_encountered_party", "p_pyongyang", "p_place_end"),
				(store_party_size_wo_prisoners, reg8, "p_main_party"),
				(party_get_slot, reg9, "p_main_party", slot_town_elder),
				(party_get_slot, reg10, "p_main_party", slot_center_player_relation),
				(display_message, "str_main_party_reportt"),
			(try_end)
		]),

	(2.0,
		[
			(try_begin),
				(this_or_next|eq, "$main_q_step", 13),
				(eq, "$main_q_step", 84),
				(try_begin),
					(eq, "$main_q_faction", "p_ruin_dummy_4"),
					(party_get_position, 11, "p_main_party"),
					(party_get_position, 12, "$main_q_faction"),
					(get_distance_between_positions, ":distance_between_positions_11_12", 11, 12),
					(try_begin),
						(lt, ":distance_between_positions_11_12", 300),
						(party_set_flags, "p_ruin_dummy_4", 256, 0),
						(party_set_flags, "p_ruin_dummy_4", 524288, 0),
						(party_set_flags, "p_ruin_dummy_4", 16384, 1),
						(party_set_icon, "p_ruin_dummy_4", "icon_wm_town_arab_2"),
						(display_message, "str_found_something", 0x0000ff00),
						(play_sound, "snd_found_something"),
						(val_add, "$main_q_step", 1),
					(try_end),
				(try_end),
				(try_begin),
					(eq, "$main_q_faction", "p_ruin_dummy_2"),
					(party_get_position, 11, "p_main_party"),
					(party_get_position, 12, "$main_q_faction"),
					(get_distance_between_positions, ":distance_between_positions_11_12", 11, 12),
					(try_begin),
						(lt, ":distance_between_positions_11_12", 300),
						(party_set_flags, "p_ruin_dummy_2", 256, 0),
						(party_set_flags, "p_ruin_dummy_2", 524288, 0),
						(party_set_flags, "p_ruin_dummy_2", 16384, 1),
						(party_set_icon, "p_ruin_dummy_2", "icon_house_exn"),
						(display_message, "str_found_something", 0x0000ff00),
						(play_sound, "snd_found_something"),
						(val_add, "$main_q_step", 1),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(gt, "$ruin_qst_target_num", 0),
				(gt, "$ruin_qst_remain_turn", 0),
				(party_get_position, 11, "p_main_party"),
				(party_get_position, 12, "$ruin_qst_target_num"),
				(get_distance_between_positions, ":distance_between_positions_11_12", 11, 12),
				(try_begin),
					(troop_get_slot, ":player_love_interest_3", "trp_player", slot_troop_love_interest_3),
					(val_mul, ":player_love_interest_3", 70),
					(val_add, ":player_love_interest_3", 100),
				(try_end),
				(try_begin),
					(lt, ":distance_between_positions_11_12", ":player_love_interest_3"),
					(neg|party_slot_ge, "$ruin_qst_target_num", 3, 2),
					(party_set_flags, "$ruin_qst_target_num", 256, 0),
					(party_set_flags, "$ruin_qst_target_num", 16384, 1),
					(party_set_slot, "$ruin_qst_target_num", slot_party_ignore_player_until, 2),
					(display_message, "str_found_something", 0x0000ff00),
					(play_sound, "snd_found_something"),
				(try_end),
			(try_end),
			(try_for_range, ":troop", "trp_tt_lord_01_00", "trp_tt_lord_end"),
				(troop_slot_ge, ":troop", 26, 1),
				(troop_get_slot, ":troop_last_quest", ":troop", slot_troop_last_quest),
				(try_begin),
					(gt, ":troop_last_quest", 0),
					(val_sub, ":troop_last_quest", 1),
					(troop_set_slot, ":troop", slot_troop_last_quest, ":troop_last_quest"),
				(else_try),
					(le, ":troop_last_quest", 0),
					(troop_set_slot, ":troop", slot_troop_last_persuasion_time, 0),
				(try_end),
			(try_end),
			(try_for_range, ":faction", "fac_neutral", "fac_ally_faction_for_slot"),
				(try_for_range, ":number", 1, 76),
					(faction_get_slot, ":faction_number", ":faction", ":number"),
					(gt, ":faction_number", 0),
					(neg|is_between, ":faction_number", "p_temp_party", "p_reserved_5"),
					(neq, ":faction_number", "p_reserved_5"),
					(party_is_active, ":faction_number"),
					(party_slot_eq, ":faction_number", slot_party_type, 4),
					(party_get_battle_opponent, ":battle_opponent_faction_number", ":faction_number"),
					(lt, ":battle_opponent_faction_number", 0),
					(call_script, "script_wm_map_icon_change_trig", ":faction_number"),
					(party_get_slot, ":faction_number_retreat_flag", ":faction_number", slot_party_retreat_flag),
					(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":faction_number", ":faction_number_retreat_flag"),
					(le, ":distance_between_positions_11_12", 1),
					(party_clear, ":faction_number"),
					(remove_party, ":faction_number"),
					(faction_set_slot, ":faction", ":number", 0),
				(try_end),
			(try_end),
			(try_for_range, ":number", 42, 44),
				(troop_get_slot, ":faction_number", "trp_player", ":number"),
				(gt, ":faction_number", 0),
				(neg|is_between, ":faction_number", "p_temp_party", "p_reserved_5"),
				(neq, ":faction_number", "p_reserved_5"),
				(party_is_active, ":faction_number"),
				(party_slot_eq, ":faction_number", slot_party_type, 5),
				(party_get_battle_opponent, ":battle_opponent_faction_number", ":faction_number"),
				(lt, ":battle_opponent_faction_number", 0),
				(call_script, "script_wm_map_icon_change_trig", ":faction_number"),
				(party_get_slot, ":faction_number_retreat_flag", ":faction_number", slot_party_retreat_flag),
				(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":faction_number", ":faction_number_retreat_flag"),
				(le, ":distance_between_positions_11_12", 1),
				(call_script, "script_traders_trade_with_town", ":faction_number", ":faction_number_retreat_flag"),
				(party_get_slot, ":faction_number_town_tavern", ":faction_number", slot_town_tavern),
				(party_get_slot, ":faction_number_town_store", ":faction_number", slot_town_store),
				(try_begin),
					(eq, ":faction_number_retreat_flag", ":faction_number_town_tavern"),
					(call_script, "script_new_party_ai", ":faction_number", 11, ":faction_number_town_store"),
				(else_try),
					(eq, ":faction_number_retreat_flag", ":faction_number_town_store"),
					(call_script, "script_new_party_ai", ":faction_number", 11, ":faction_number_town_tavern"),
				(try_end),
			(try_end),
			(store_random_in_range, ":troop_last_quest", 42, 44),
			(troop_get_slot, ":player_troop_last_quest", "trp_player", ":troop_last_quest"),
			(assign, ":value", 0),
			(try_begin),
				(neq, ":player_troop_last_quest", "p_main_party"),
				(neg|is_between, ":player_troop_last_quest", "p_temp_party", "p_reserved_5"),
				(neq, ":player_troop_last_quest", "p_reserved_5"),
				(party_is_active, ":player_troop_last_quest"),
				(assign, ":value", 1),
			(try_end),
			(try_for_range, ":faction", "fac_commoners", "fac_neutral"),
				(assign, ":var_14", ":faction"),
				(try_for_range, ":number", 0, 76),
					(faction_get_slot, ":var_14_number", ":var_14", ":number"),
					(gt, ":var_14_number", 0),
					(neg|is_between, ":var_14_number", "p_temp_party", "p_reserved_5"),
					(neq, ":var_14_number", "p_reserved_5"),
					(party_is_active, ":var_14_number"),
					(party_slot_eq, ":var_14_number", slot_party_type, 2),
					(party_get_battle_opponent, ":battle_opponent_var_14_number", ":var_14_number"),
					(lt, ":battle_opponent_var_14_number", 0),
					(call_script, "script_wm_map_icon_change_trig", ":var_14_number"),
					(party_get_slot, ":var_14_number_1", ":var_14_number", 1),
					(party_get_slot, ":var_14_number_town_prison", ":var_14_number", slot_town_prison),
					(party_get_slot, ":faction_number_retreat_flag", ":var_14_number", slot_party_retreat_flag),
					(store_party_size_wo_prisoners, ":party_size_wo_prisoners_var_14_number", ":var_14_number"),
					(try_begin),
						(le, ":party_size_wo_prisoners_var_14_number", 80),
						(store_random_in_range, ":random_in_range_0_3", 0, 3),
						(eq, ":random_in_range_0_3", 0),
						(call_script, "script_party_army_size_execute", ":var_14_number", 1, 87),
					(try_end),
					(try_begin),
						(eq, ":var_14_number_1", 3),
						(party_get_slot, ":var_14_number_center_accumulated_tariffs", ":var_14_number", slot_center_accumulated_tariffs),
						(val_add, ":var_14_number_center_accumulated_tariffs", 1),
						(party_set_slot, ":var_14_number", slot_center_accumulated_tariffs, ":var_14_number_center_accumulated_tariffs"),
					(try_end),
					(try_begin),
						(eq, ":var_14_number_1", 3),
						(neg|party_is_active, ":faction_number_retreat_flag"),
						(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
					(else_try),
						(eq, ":var_14_number_1", 3),
						(party_get_battle_opponent, ":battle_opponent_faction_number", ":faction_number_retreat_flag"),
						(ge, ":battle_opponent_faction_number", 0),
						(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
					(else_try),
						(party_slot_eq, ":faction_number_retreat_flag", slot_party_last_toll_paid_hours, 5),
						(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
					(else_try),
						(eq, ":var_14_number_1", 3),
						(party_slot_ge, ":var_14_number", 48, 4),
						(call_script, "script_new_party_ai", ":var_14_number", 6, ":var_14_number_town_prison"),
						(party_set_slot, ":var_14_number", slot_center_accumulated_tariffs, 0),
					(else_try),
						(eq, ":var_14_number_1", 6),
						(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":var_14_number", ":var_14_number_town_prison"),
						(le, ":distance_between_positions_11_12", 4),
						(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
					(else_try),
						(neq, ":var_14_number_1", 3),
						(neq, ":var_14_number_1", 6),
						(call_script, "script_party_count_fit_for_battle", ":var_14_number"),
						(assign, ":value_2", reg0),
						(assign, ":value_3", 76),
						(assign, ":value_4", 0),
						(try_for_range, ":faction_2", "fac_neutral", "fac_ally_faction_for_slot"),
							(eq, ":value_4", 0),
							(try_for_range, ":number", 0, ":value_3"),
								(eq, ":value_4", 0),
								(faction_get_slot, ":faction_2_number", ":faction_2", ":number"),
								(try_begin),
									(eq, ":faction_2", "fac_neutral"),
									(eq, ":number", 0),
									(assign, ":faction_2_number", "p_main_party"),
								(else_try),
									(eq, ":value", 1),
									(eq, ":number", 0),
									(assign, ":faction_2_number", ":player_troop_last_quest"),
								(else_try),
									(eq, ":number", 0),
									(assign, ":faction_2_number", "p_main_party"),
								(try_end),
								(ge, ":faction_2_number", 0),
								(neg|is_between, ":faction_2_number", "p_temp_party", "p_reserved_5"),
								(neq, ":faction_2_number", "p_reserved_5"),
								(party_is_active, ":faction_2_number"),
								(party_slot_eq, ":faction_2_number", slot_party_last_toll_paid_hours, 0),
								(assign, ":value_5", 0),
								(try_begin),
									(neq, ":number", 0),
									(party_slot_eq, ":faction_2_number", slot_party_type, 4),
									(party_get_battle_opponent, ":battle_opponent_faction_2_number", ":faction_2_number"),
									(lt, ":battle_opponent_faction_2_number", 0),
									(assign, ":value_5", 1),
								(else_try),
									(eq, ":number", 0),
									(assign, ":value_5", 1),
								(try_end),
								(eq, ":value_5", 1),
								(call_script, "script_party_count_fit_for_battle", ":faction_2_number"),
								(assign, ":value_6", reg0),
								(ge, ":value_2", ":value_6"),
								(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":var_14_number", ":faction_2_number"),
								(le, ":distance_between_positions_11_12", "$encount_dist"),
								(call_script, "script_new_party_ai", ":var_14_number", 3, ":faction_2_number"),
								(assign, ":value_4", 1),
								(store_add, ":value_3", ":number", 1),
							(try_end),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(try_for_range, ":number", 0, 29),
				(faction_get_slot, ":var_14_number", "fac_hot_points", ":number"),
				(gt, ":var_14_number", 0),
				(neg|is_between, ":var_14_number", "p_temp_party", "p_reserved_5"),
				(neq, ":var_14_number", "p_reserved_5"),
				(party_is_active, ":var_14_number"),
				(party_slot_eq, ":var_14_number", slot_party_type, 3),
				(party_get_battle_opponent, ":battle_opponent_var_14_number", ":var_14_number"),
				(lt, ":battle_opponent_var_14_number", 0),
				(call_script, "script_wm_map_icon_change_trig", ":var_14_number"),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_var_14_number", ":var_14_number"),
				(try_begin),
					(le, ":party_size_wo_prisoners_var_14_number", 80),
					(store_random_in_range, ":random_in_range_0_3", 0, 3),
					(eq, ":random_in_range_0_3", 0),
					(call_script, "script_party_army_size_execute", ":var_14_number", 1, 87),
				(try_end),
				(party_get_slot, ":var_14_number_1", ":var_14_number", 1),
				(party_get_slot, ":var_14_number_town_prison", ":var_14_number", slot_town_prison),
				(party_get_slot, ":faction_number_retreat_flag", ":var_14_number", slot_party_retreat_flag),
				(party_get_current_terrain, ":current_terrain_var_14_number", ":var_14_number"),
				(try_begin),
					(eq, ":var_14_number_1", 3),
					(party_get_slot, ":var_14_number_center_accumulated_tariffs", ":var_14_number", slot_center_accumulated_tariffs),
					(val_add, ":var_14_number_center_accumulated_tariffs", 1),
					(party_set_slot, ":var_14_number", slot_center_accumulated_tariffs, ":var_14_number_center_accumulated_tariffs"),
				(try_end),
				(try_begin),
					(neq, ":current_terrain_var_14_number", 7),
					(neq, ":current_terrain_var_14_number", 2),
					(call_script, "script_new_party_ai", ":var_14_number", 6, ":var_14_number_town_prison"),
				(else_try),
					(eq, ":var_14_number_1", 3),
					(neg|party_is_active, ":faction_number_retreat_flag"),
					(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
				(else_try),
					(eq, ":var_14_number_1", 3),
					(party_get_battle_opponent, ":battle_opponent_faction_number", ":faction_number_retreat_flag"),
					(ge, ":battle_opponent_faction_number", 0),
					(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
				(else_try),
					(eq, ":var_14_number_1", 3),
					(party_slot_ge, ":var_14_number", 48, 4),
					(call_script, "script_new_party_ai", ":var_14_number", 6, ":var_14_number_town_prison"),
					(party_set_slot, ":var_14_number", slot_center_accumulated_tariffs, 0),
				(else_try),
					(eq, ":var_14_number_1", 6),
					(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":var_14_number", ":var_14_number_town_prison"),
					(le, ":distance_between_positions_11_12", 4),
					(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
				(else_try),
					(neq, ":var_14_number_1", 3),
					(neq, ":var_14_number_1", 6),
					(call_script, "script_party_count_fit_for_battle", ":var_14_number"),
					(assign, ":value_2", reg0),
					(assign, ":value_3", 76),
					(assign, ":value_4", 0),
					(try_for_range, ":faction_2", "fac_neutral", "fac_ally_faction_for_slot"),
						(eq, ":value_4", 0),
						(try_for_range, ":number", 0, ":value_3"),
							(eq, ":value_4", 0),
							(faction_get_slot, ":faction_2_number", ":faction_2", ":number"),
							(try_begin),
								(eq, ":faction_2", "fac_neutral"),
								(eq, ":number", 0),
								(assign, ":faction_2_number", "p_main_party"),
							(else_try),
								(eq, ":value", 1),
								(eq, ":number", 0),
								(assign, ":faction_2_number", ":player_troop_last_quest"),
							(else_try),
								(eq, ":number", 0),
								(assign, ":faction_2_number", "p_main_party"),
							(try_end),
							(ge, ":faction_2_number", 0),
							(neg|is_between, ":faction_2_number", "p_temp_party", "p_reserved_5"),
							(neq, ":faction_2_number", "p_reserved_5"),
							(party_is_active, ":faction_2_number"),
							(party_slot_eq, ":faction_2_number", slot_party_last_toll_paid_hours, 0),
							(assign, ":value_5", 0),
							(try_begin),
								(neq, ":number", 0),
								(party_slot_eq, ":faction_2_number", slot_party_type, 4),
								(party_get_battle_opponent, ":battle_opponent_faction_2_number", ":faction_2_number"),
								(lt, ":battle_opponent_faction_2_number", 0),
								(assign, ":value_5", 1),
							(else_try),
								(eq, ":number", 0),
								(assign, ":value_5", 1),
							(try_end),
							(eq, ":value_5", 1),
							(call_script, "script_party_count_fit_for_battle", ":faction_2_number"),
							(assign, ":value_6", reg0),
							(ge, ":value_2", ":value_6"),
							(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":var_14_number", ":faction_2_number"),
							(le, ":distance_between_positions_11_12", "$encount_dist"),
							(call_script, "script_new_party_ai", ":var_14_number", 3, ":faction_2_number"),
							(assign, ":value_4", 1),
							(store_add, ":value_3", ":number", 1),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$main_q_step", 1),
				(eq, "$step_1", 0),
				(assign, "$step_1", 1),
				(display_message, "str_mq_camp_menu_tip_ala", 0x00ffff00),
				(dialog_box, "str_mq_camp_menu_tip_ala", "@Main Quest"),
			(else_try),
				(eq, "$main_q_step", 2),
				(eq, "$step_2", 0),
				(assign, "$step_2", 1),
				(neg|is_between, "$rt_marked_target", "p_pyongyang", "p_place_end"),
				(display_message, "str_mq_camp_menu_tip_ala", 0x00ffff00),
				(dialog_box, "str_mq_camp_menu_tip_ala", "@Main Quest"),
			(try_end)
		]),

	(1.0,
		[
		(music_set_situation, 0x00010000),
			(try_begin),
				(neq, "$camera_focus_on", 0),
				(set_camera_follow_party, "p_main_party"),
				(assign, "$camera_focus_on", 0),
			(try_end),
			(try_begin),
				(is_currently_night),
				(assign, "$battle_join_dist", 1),
			(else_try),
				(assign, "$battle_join_dist", 3),
			(try_end),
			(call_script, "script_faction_army_list_scan"),
			(try_begin),
				(ge, "$hourr_count", 24),
				(assign, "$hourr_count", 1),
				#(display_message, "@Testing 24 hrs"),
				(try_begin),
				(eq, "$started_as_monarch", 1),
				(assign, "$started_as_monarch", 0),
				(assign, "$progress_civilwar", 1),
				(assign, "$attempt_coup", 1),
				(jump_to_menu, "mnu_coup_progress"),
				(try_end),
				
				(try_begin),
				(eq, "$started_as_monarch", 2),
				(assign, "$started_as_monarch", 0),
				#additions
				(assign, "$progress_civilwar", 0),
				(assign, "$attempt_coup", 1),
				#additions
				(jump_to_menu, "mnu_coup_success"),
				(try_end),
				
			(else_try),
				(val_add, "$hourr_count", 1),
				#(display_message, "@Adding 1  hr"),
			(try_end),
			(try_begin),
				(gt, "$wm_buying_drink_for_army", 0),
				(val_sub, "$wm_buying_drink_for_army", 1),
			(try_end),
			(try_begin),
				(gt, "$attemp_commu", 0),
				(val_sub, "$attemp_commu", 1),
			(try_end),
			(try_begin),
				(gt, "$bet_already", 0),
				(val_sub, "$bet_already", 1),
			(try_end),
			(try_begin),
				(gt, "$innocent_pay", 0),
				(val_sub, "$innocent_pay", 1),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 2),
				(eq, "$hourr_count", 16),
				(try_begin),
					(eq, "$weekk_count", 2),
					(eq, "$adult_content", 1),
					(troop_slot_eq, "trp_player", slot_troop_last_persuasion_time, 1),
					(call_script, "script_troop_type_sett", "trp_player"),
					(gt, "$troop_gender_type", 10),
					(call_script, "script_adv_exp_diff", 150, 87),
					(display_message, "str_virgin_adv_bonus", 0x00ff9000),
				(try_end),
				(try_begin),
					(eq, "$r_player_class", 3),
					(call_script, "script_wm_honor_change_diff", "trp_player", 1, 87),
					(display_message, "str_lord_honor_bonus", 0x00ff9000),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$trade_guild_info_on", 1),
				(assign, "$trade_guild_info_on", 0),
				(display_message, "str_trade_info_end", 0x00ff9000),
			(try_end),
			(try_begin),
				(eq, "$hourr_count", 13),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party", "p_main_party"),
				(try_begin),
					(ge, ":party_size_wo_prisoners_main_party", 10),
					(val_div, ":party_size_wo_prisoners_main_party", 5),
					(party_get_slot, ":main_party_center_siege_with_belfry", "p_main_party", slot_center_siege_with_belfry),
					(try_begin),
						(lt, ":main_party_center_siege_with_belfry", ":party_size_wo_prisoners_main_party"),
						(display_message, "str_food_loww", 0x00ff0000),
						(call_script, "script_party_food_level_diff", "p_main_party", ":party_size_wo_prisoners_main_party", 34),
						(call_script, "script_moral_level_diff", "p_main_party", -50),
						(call_script, "script_wm_after_battle_health_result"),
					(else_try),
						(call_script, "script_party_food_level_diff", "p_main_party", ":party_size_wo_prisoners_main_party", 34),
					(try_end),
				(try_end),
				(party_get_slot, ":main_party_center_player_relation", "p_main_party", slot_center_player_relation),
				(try_begin),
					(lt, ":main_party_center_player_relation", 45),
					(call_script, "script_party_army_size_execute", "p_main_party", 85, 3),
					(call_script, "script_stack_kill_sc", 15, 0, 2, 1),
					(display_message, "str_moral_loww", 0x00ff0000),
				(try_end),
			(try_end),
			(call_script, "script_player_fix_army_size"),
			(try_begin),
				(map_free),
				(assign, "$player_recruit_train_start", 0),
				(neg|party_slot_eq, "p_main_party", slot_party_last_toll_paid_hours, 0),
				(party_set_slot, "p_main_party", slot_party_last_toll_paid_hours, 0),
			(try_end),
			(try_begin),
				(gt, "$player_recruit_train_start", 0),
				(try_begin),
					(neg|map_free),
					(is_between, "$g_encountered_party", "p_pyongyang", "p_place_end"),
					(store_faction_of_party, ":faction_of_party_g_encountered_party", "$g_encountered_party"),
					(assign, ":value", "$wm_player_fac"),
					(assign, ":value_2", "$g_encountered_party"),
					(assign, ":value_3", "p_main_party"),
					(try_begin),
						(neg|party_slot_eq, ":value_3", slot_party_last_toll_paid_hours, 5),
						(party_set_slot, ":value_3", slot_party_last_toll_paid_hours, 5),
					(try_end),
					(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_3", ":value_3"),
					(party_get_slot, ":value_2_town_alley", ":value_2", slot_town_alley),
					(try_begin),
						(lt, ":value_2_town_alley", 10),
						(assign, ":value_2_town_alley", 10),
					(try_end),
					(val_mul, ":value_2_town_alley", 160),
					(val_div, ":value_2_town_alley", 100),
					(call_script, "script_moral_level_diff", ":value_3", 1),
					(try_begin),
						(eq, "$player_recruit_train_start", 2),
						(try_begin),
							(ge, ":party_size_wo_prisoners_value_3", 1000),
							(store_div, ":value_4", ":party_size_wo_prisoners_value_3", 1000),
						(else_try),
							(assign, ":value_4", 5),
						(try_end),
						(call_script, "script_party_money_level_ge", "p_main_party", ":value_4"),
						(try_begin),
							(eq, "$hourr_count", 12),
							(eq, "$wm_mo_continue", 1),
							(call_script, "script_exp_reward_for_common_troop", 1),
							(call_script, "script_party_money_level_diff", ":value_3", ":value_4", 34),
							(val_mul, ":value_4", 24),
							(assign, reg8, ":value_4"),
							(display_message, "str_traincostreg8"),
						(else_try),
							(eq, "$wm_mo_continue", 1),
							(call_script, "script_exp_reward_for_common_troop", 1),
							(call_script, "script_party_money_level_dif_no_mes", ":value_3", ":value_4", 34),
						(else_try),
							(neq, "$wm_mo_continue", 1),
							(eq, "$hourr_count", 12),
							(display_message, "str_nomoney", 0x00ff0000),
						(try_end),
						(call_script, "script_train_level_diff", ":value_3", 1),
					(try_end),
					(try_begin),
						(neq, ":faction_of_party_g_encountered_party", "$wm_player_fac"),
						(val_mul, ":value_2_town_alley", 40),
						(val_div, ":value_2_town_alley", 100),
						(try_begin),
							(eq, "$player_recruit_train_start", 1),
							(eq, "$hourr_count", 14),
							(display_message, "str_recruit_quarter", 0x00ffff00),
						(try_end),
					(else_try),
						(neg|party_slot_eq, "$g_encountered_party", slot_town_tavern, "trp_player"),
						(val_mul, ":value_2_town_alley", 66),
						(val_div, ":value_2_town_alley", 100),
						(try_begin),
							(eq, "$player_recruit_train_start", 1),
							(eq, "$hourr_count", 14),
							(display_message, "str_recruit_half", 0x00ffff00),
						(try_end),
					(try_end),
					(try_begin),
						(eq, "$player_recruit_train_start", 1),
						(try_begin),
							(lt, ":party_size_wo_prisoners_value_3", 500),
							(assign, ":value_2_town_alley", 500),
							(assign, ":value_5", 500),
							(try_begin),
								(call_script, "script_party_money_level_ge", "p_main_party", ":value_5"),
								(eq, "$wm_mo_continue", 1),
								(dialog_box, "str_recruit_regular_army", "str_box_note"),
							(try_end),
						(else_try),
							(store_div, ":value_5", ":value_2_town_alley", 2),
						(try_end),
						(call_script, "script_party_money_level_ge", "p_main_party", ":value_5"),
						(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party_2", "p_main_party"),
						(try_begin),
							(eq, "$hourr_count", 12),
							(eq, "$wm_mo_continue", 1),
							(call_script, "script_party_army_size_execute", ":value_3", ":value_2_town_alley", 87),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party_3", "p_main_party"),
							(neq, ":party_size_wo_prisoners_main_party_2", ":party_size_wo_prisoners_main_party_3"),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
							(try_begin),
								(gt, ":party_size_wo_prisoners_value_2", 10000),
								(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
							(try_end),
							(call_script, "script_party_money_level_diff", ":value_3", ":value_5", 34),
							(val_mul, ":value_5", 24),
							(assign, reg8, ":value_5"),
							(display_message, "str_recruitcostreg8"),
						(else_try),
							(eq, "$wm_mo_continue", 1),
							(call_script, "script_party_army_size_execute", ":value_3", ":value_2_town_alley", 87),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party_3", "p_main_party"),
							(neq, ":party_size_wo_prisoners_main_party_2", ":party_size_wo_prisoners_main_party_3"),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
							(try_begin),
								(gt, ":party_size_wo_prisoners_value_2", 8000),
								(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
							(try_end),
							(call_script, "script_party_money_level_dif_no_mes", ":value_3", ":value_5", 34),
						(else_try),
							(neq, "$wm_mo_continue", 1),
							(eq, "$hourr_count", 12),
							(display_message, "str_nomoney", 0x00ff0000),
						(try_end),
					(try_end),
					(call_script, "script_party_food_level_dif_no_mes", ":value_3", 20000, 87),
				(try_end),
			(try_end),
			(try_begin),
				(is_between, "$ply_staying_party_no", "p_pyongyang", "p_place_end"),
				(eq, "$ply_staying_army_recruit_on", 1),
				(assign, ":value_2", "$ply_staying_party_no"),
				(troop_get_slot, ":player_betrothed", "trp_player", slot_troop_betrothed),
				(val_clamp, ":player_betrothed", 0, 7),
				(store_mul, ":value_6", ":player_betrothed", 500),
				(store_mul, ":value_7", 100, 70),
				(val_add, ":value_7", ":value_6"),
				(lt, "$ply_staying_army_size", ":value_7"),
				(party_get_slot, ":value_2_town_alley", ":value_2", slot_town_alley),
				(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_2"),
				(try_begin),
					(neq, ":faction_of_party_g_encountered_party", "$wm_player_fac"),
					(val_mul, ":value_2_town_alley", 40),
					(val_div, ":value_2_town_alley", 100),
				(else_try),
					(neg|party_slot_eq, ":value_2", slot_town_tavern, "trp_player"),
					(val_mul, ":value_2_town_alley", 66),
					(val_div, ":value_2_town_alley", 100),
				(try_end),
				(store_div, ":value_5", ":value_2_town_alley", 2),
				(call_script, "script_party_money_level_ge", "p_main_party", ":value_5"),
				(eq, "$wm_mo_continue", 1),
				(assign, ":var_18", "$ply_staying_army_size"),
				(val_add, "$ply_staying_army_size", ":value_2_town_alley"),
				(try_begin),
					(gt, "$ply_staying_army_size", ":value_7"),
					(assign, "$ply_staying_army_size", ":value_7"),
				(try_end),
				(neq, ":var_18", "$ply_staying_army_size"),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
				(try_begin),
					(gt, ":party_size_wo_prisoners_value_2", 10000),
					(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
				(try_end),
				(call_script, "script_party_money_level_dif_no_mes", "p_main_party", ":value_5", 34),
			(try_end),
			(try_begin),
				(eq, "$hourr_count", 15),
				(call_script, "script_common_prisoner_escape"),
				(store_random_in_range, "$disaster_occur_time", 1, 25),
			(try_end),
			(try_begin),
				(eq, "$hourr_count", "$disaster_occur_time"),
				(party_get_current_terrain, ":current_terrain_main_party", "p_main_party"),
				(store_random_in_range, ":random_in_range_0_20", 0, 20),
				(try_begin),
					(eq, ":current_terrain_main_party", 4),
					(eq, ":random_in_range_0_20", 0),
					(neq, "$wm_player_fac", "fac_kingdom_7"),
					(neq, "$wm_player_fac", "fac_kingdom_10"),
					(neq, "$wm_player_fac", "fac_kingdom_12"),
					(neq, "$wm_player_fac", "fac_kingdom_16"),
					(neq, "$wm_player_fac", "fac_kingdom_29"),
					(neq, "$wm_player_fac", "fac_kingdom_30"),
					(neq, "$wm_player_fac", "fac_kingdom_47"),
					(neq, "$wm_player_fac", "fac_kingdom_48"),
					(neq, "$wm_player_fac", "fac_kingdom_50"),
					(neq, "$wm_player_fac", "fac_kingdom_52"),
					(neq, "$wm_player_fac", "fac_kingdom_53"),
					(neq, "$wm_player_fac", "fac_kingdom_54"),
					(party_relocate_near_party, "p_disaster_ice_ply", "p_main_party", 0),
					(party_set_flags, "p_disaster_ice_ply", 256, 0),
					(str_store_party_name, 11, "p_main_party"),
					(display_message, "str_disaster_coldbringer", 0x00ff0000),
					(play_sound, "snd_Typhoon"),
					(assign, "$ply_timer_fall_disaster", 24),
					(troop_get_slot, ":player_love_interest_1", "trp_player", slot_troop_love_interest_1),
					(store_random_in_range, ":random_in_range_0_7", 0, 7),
					(try_begin),
						(lt, ":random_in_range_0_7", ":player_love_interest_1"),
						(display_message, "str_logistics_avoid", 0x0000ff00),
					(else_try),
						(call_script, "script_party_army_size_execute", "p_main_party", 75, 3),
						(call_script, "script_moral_level_diff", "p_main_party", -30),
						(call_script, "script_wm_after_battle_health_result"),
						(call_script, "script_stack_kill_sc", 25, 0, 1, 1),
					(try_end),
				(else_try),
					(eq, ":current_terrain_main_party", 5),
					(eq, ":random_in_range_0_20", 0),
					(neq, "$wm_player_fac", "fac_kingdom_2"),
					(neq, "$wm_player_fac", "fac_kingdom_3"),
					(neq, "$wm_player_fac", "fac_kingdom_4"),
					(neq, "$wm_player_fac", "fac_kingdom_6"),
					(neq, "$wm_player_fac", "fac_kingdom_9"),
					(neq, "$wm_player_fac", "fac_kingdom_13"),
					(neq, "$wm_player_fac", "fac_kingdom_14"),
					(neq, "$wm_player_fac", "fac_kingdom_21"),
					(neq, "$wm_player_fac", "fac_kingdom_22"),
					(neq, "$wm_player_fac", "fac_kingdom_30"),
					(neq, "$wm_player_fac", "fac_kingdom_31"),
					(neq, "$wm_player_fac", "fac_kingdom_32"),
					(neq, "$wm_player_fac", "fac_kingdom_34"),
					(neq, "$wm_player_fac", "fac_kingdom_40"),
					(neq, "$wm_player_fac", "fac_kingdom_41"),
					(neq, "$wm_player_fac", "fac_kingdom_44"),
					(neq, "$wm_player_fac", "fac_kingdom_49"),
					(neq, "$wm_player_fac", "fac_kingdom_51"),
					(neq, "$wm_player_fac", "fac_kingdom_52"),
					(neq, "$wm_player_fac", "fac_africa_people"),
					(neq, "$wm_player_fac", "fac_hindu_people"),
					(neq, "$wm_player_fac", "fac_arabian_people"),
					(party_relocate_near_party, "p_disaster_sand_ply", "p_main_party", 0),
					(party_set_flags, "p_disaster_sand_ply", 256, 0),
					(str_store_party_name, 11, "p_main_party"),
					(display_message, "str_disaster_sand_storm", 0x00ff0000),
					(play_sound, "snd_Typhoon"),
					(assign, "$ply_timer_fall_disaster", 24),
					(troop_get_slot, ":player_love_interest_1", "trp_player", slot_troop_love_interest_1),
					(store_random_in_range, ":random_in_range_0_7", 0, 7),
					(try_begin),
						(lt, ":random_in_range_0_7", ":player_love_interest_1"),
						(display_message, "str_logistics_avoid", 0x0000ff00),
					(else_try),
						(call_script, "script_party_army_size_execute", "p_main_party", 85, 3),
						(call_script, "script_moral_level_diff", "p_main_party", -30),
						(call_script, "script_wm_after_battle_health_result"),
						(call_script, "script_stack_kill_sc", 15, 0, 1, 1),
					(try_end),
				(else_try),
					(this_or_next|eq, ":current_terrain_main_party", 7),
					(eq, ":current_terrain_main_party", 2),
					(eq, ":random_in_range_0_20", 0),
					(party_relocate_near_party, "p_disaster_storm_ply", "p_main_party", 0),
					(party_set_flags, "p_disaster_storm_ply", 256, 0),
					(str_store_party_name, 11, "p_main_party"),
					(display_message, "str_disaster_storm", 0x00ff0000),
					(play_sound, "snd_Flood"),
					(assign, "$ply_timer_fall_disaster", 24),
					(troop_get_slot, ":player_love_interest_1", "trp_player", slot_troop_love_interest_1),
					(store_random_in_range, ":random_in_range_0_7", 0, 7),
					(try_begin),
						(call_script, "script_wm_main_party_has_troop_sc", "trp_npc1"),
						(eq, "$wm_comp_continue", 1),
						(display_message, "str_disaster_storm_alonso", 0x0000ff00),
					(else_try),
						(lt, ":random_in_range_0_7", ":player_love_interest_1"),
						(display_message, "str_navigation_avoid", 0x0000ff00),
					(else_try),
						(call_script, "script_party_army_size_execute", "p_main_party", 60, 3),
						(call_script, "script_moral_level_diff", "p_main_party", -35),
						(call_script, "script_wm_after_battle_health_result"),
						(call_script, "script_stack_kill_sc", 40, 0, 1, 1),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(gt, "$ply_timer_fall_disaster", 0),
				(val_sub, "$ply_timer_fall_disaster", 1),
			(else_try),
				(eq, "$ply_timer_fall_disaster", 0),
				(party_set_flags, "p_disaster_storm_ply", 256, 1),
				(party_set_flags, "p_disaster_sand_ply", 256, 1),
				(party_set_flags, "p_disaster_ice_ply", 256, 1),
			(try_end),
			(call_script, "script_morale_train_event", "p_main_party"),
			(try_for_range, ":value", "fac_kingdom_1", "fac_undeads"),
				(faction_slot_eq, ":value", slot_faction_player_alarm, 1),
				(try_for_range, ":number", 56, 76),
					(faction_get_slot, ":value_3", ":value", ":number"),
					(gt, ":value_3", 0),
					(neg|is_between, ":value_3", "p_temp_party", "p_reserved_5"),
					(neq, ":value_3", "p_reserved_5"),
					(party_is_active, ":value_3"),
					(party_slot_eq, ":value_3", slot_party_type, 1),
					(call_script, "script_wm_map_icon_change_trig", ":value_3"),
					(party_get_battle_opponent, ":battle_opponent_value_3", ":value_3"),
					(try_begin),
						(lt, ":battle_opponent_value_3", 0),
						(call_script, "script_morale_train_event", ":value_3"),
					(try_end),
					(try_begin),
						(lt, ":battle_opponent_value_3", 0),
						(store_random_in_range, ":random_in_range_0_20", 0, 300),
						(try_begin),
							(eq, ":random_in_range_0_20", 0),
							(call_script, "script_ai_suffer_storm", ":value_3", 1, ":value"),
						(else_try),
							(eq, ":random_in_range_0_20", 1),
							(call_script, "script_ai_suffer_storm", ":value_3", 2, ":value"),
						(else_try),
							(eq, ":random_in_range_0_20", 2),
							(call_script, "script_ai_suffer_storm", ":value_3", 3, ":value"),
						(try_end),
					(try_end),
					(call_script, "script_party_count_fit_for_battle", ":value_3"),
					(assign, ":var_25", reg0),
					(faction_get_slot, ":value_28", ":value", 28),
					(faction_get_slot, ":value_number_of_parties", ":value", slot_faction_number_of_parties),
					(faction_get_slot, ":value_state", ":value", slot_faction_state),
					(party_get_slot, ":value_3_1", ":value_3", 1),
					(party_get_slot, ":value_3_town_prosperity", ":value_3", slot_town_prosperity),
					(party_get_slot, ":value_3_retreat_flag", ":value_3", slot_party_retreat_flag),
					(party_get_slot, ":value_3_town_prison", ":value_3", slot_town_prison),
					(store_faction_of_party, ":faction_of_party_value_3_town_prison", ":value_3_town_prison"),
					(try_begin),
						(neq, ":faction_of_party_value_3_town_prison", ":value"),
						(call_script, "script_home_land_sett_retry", ":value_3", ":value"),
						(party_get_slot, ":value_3_town_prison", ":value_3", slot_town_prison),
					(else_try),
						(neg|is_between, ":value_3_town_prison", "p_pyongyang", "p_place_end"),
						(call_script, "script_home_land_sett_retry", ":value_3", ":value"),
						(party_get_slot, ":value_3_town_prison", ":value_3", slot_town_prison),
					(try_end),
					(assign, ":value_8", 0),
					(try_begin),
						(is_between, ":value_3_town_prison", "p_pyongyang", "p_place_end"),
						(store_faction_of_party, ":faction_of_party_value_3_town_prison", ":value_3_town_prison"),
						(eq, ":faction_of_party_value_3_town_prison", ":value"),
						(assign, ":value_8", 1),
					(try_end),
					(store_mul, ":value_7", 100, 70),
					(party_stack_get_troop_id, ":party_stack_troop_id_value_3_0", ":value_3", 0),
					(try_begin),
						(is_between, ":party_stack_troop_id_value_3_0", "trp_tt_lord_01_00", "trp_tt_lord_end"),
						(troop_get_slot, ":player_betrothed", ":party_stack_troop_id_value_3_0", slot_troop_betrothed),
						(val_clamp, ":player_betrothed", 0, 7),
						(store_mul, ":value_6", ":player_betrothed", 500),
						(val_add, ":value_7", ":value_6"),
					(try_end),
					(party_get_slot, ":value_3_last_toll_paid_hours", ":value_3", slot_party_last_toll_paid_hours),
					(party_get_attached_to, ":attached_to_value_3", ":value_3"),
					(assign, ":value_2", 0),
					(try_begin),
						(is_between, ":attached_to_value_3", "p_pyongyang", "p_place_end"),
						(assign, ":value_2", ":attached_to_value_3"),
						(try_begin),
							(neq, ":value_3_last_toll_paid_hours", 5),
							(party_set_slot, ":value_3", slot_party_last_toll_paid_hours, 5),
						(try_end),
					(else_try),
						(neq, ":value_3_last_toll_paid_hours", 0),
						(party_set_slot, ":value_3", slot_party_last_toll_paid_hours, 0),
					(try_end),
					(party_get_slot, ":value_3_center_accumulated_tariffs", ":value_3", slot_center_accumulated_tariffs),
					(try_begin),
						(eq, ":value_3_1", 3),
						(val_add, ":value_3_center_accumulated_tariffs", 1),
						(party_set_slot, ":value_3", slot_center_accumulated_tariffs, ":value_3_center_accumulated_tariffs"),
					(try_end),
					(assign, ":value_9", 0),
					(assign, ":value_10", 1),
					(try_begin),
						(le, ":value_28", 0),
						(eq, ":value_2", 0),
						(gt, ":value_3_town_prosperity", 0),
						(eq, ":value_8", 1),
						(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
					(else_try),
						(neg|is_between, ":value_3_retreat_flag", "p_temp_party", "p_reserved_5"),
						(neq, ":value_3_retreat_flag", "p_reserved_5"),
						(party_is_active, ":value_3_retreat_flag"),
						(party_slot_eq, ":value_3_retreat_flag", slot_party_last_toll_paid_hours, 5),
						(eq, ":value_8", 1),
						(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
					(else_try),
						(party_slot_ge, ":value_3", 48, 4),
						(eq, ":value_8", 1),
						(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
						(party_set_slot, ":value_3", slot_center_accumulated_tariffs, 0),
						(assign, ":value_9", 1),
					(else_try),
						(gt, ":var_25", 2100),
						(eq, ":value_2", 0),
						(neq, ":value_3_1", 6),
						(lt, ":battle_opponent_value_3", 0),
						(faction_set_slot, "fac_player_supporters_faction", slot_faction_village_walker_female_troop, "p_main_party"),
						(assign, ":var_41", "fac_player_supporters_faction"),
						(assign, ":value_11", "fac_undeads"),
						(try_for_range, ":var_43", ":var_41", ":value_11"),
							(eq, ":value_10", 1),
							(store_relation, ":relation_value_var_43", ":value", ":var_43"),
							(lt, ":relation_value_var_43", 0),
							(assign, ":value_12", 76),
							(try_for_range, ":localvariable", 56, ":value_12"),
								(faction_get_slot, ":var_43_localvariable", ":var_43", ":localvariable"),
								(try_begin),
									(this_or_next|eq, ":var_43", "fac_kingdoms_end"),
									(eq, ":var_43", "fac_player_supporters_faction"),
									(assign, ":var_43_localvariable", "p_main_party"),
								(try_end),
								(ge, ":var_43_localvariable", 0),
								(neg|is_between, ":var_43_localvariable", "p_temp_party", "p_reserved_5"),
								(neq, ":var_43_localvariable", "p_reserved_5"),
								(party_is_active, ":var_43_localvariable"),
								(party_slot_eq, ":var_43_localvariable", slot_party_last_toll_paid_hours, 0),
								(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":var_43_localvariable"),
								(le, ":distance_to_party_from_party_value_3_var_43_localvariable", "$encount_dist"),
								(call_script, "script_party_count_fit_for_battle", ":var_43_localvariable"),
								(assign, ":var_49", reg0),
								(set_show_messages, 0),
								(store_mul, ":value_13", ":var_49", 75),
								(val_div, ":value_13", 100),
								(set_show_messages, 1),
								(store_random_in_range, ":random_in_range_0_10", 0, 10),
								(try_begin),
									(ge, ":var_25", ":var_49"),
									(call_script, "script_new_party_ai", ":value_3", 3, ":var_43_localvariable"),
									(assign, ":value_10", 0),
									(assign, ":value_11", ":var_43"),
									(val_add, ":value_11", 1),
									(assign, ":value_12", ":localvariable"),
									(val_add, ":value_12", 1),
									(assign, ":value_9", 1),
								(else_try),
									(is_between, ":var_25", ":value_13", ":var_49"),
									(lt, ":random_in_range_0_10", 5),
									(call_script, "script_new_party_ai", ":value_3", 3, ":var_43_localvariable"),
									(assign, ":value_10", 0),
									(assign, ":value_11", ":var_43"),
									(val_add, ":value_11", 1),
									(assign, ":value_12", ":localvariable"),
									(val_add, ":value_12", 1),
									(assign, ":value_9", 1),
								(else_try),
									(call_script, "script_new_party_ai", ":value_3", 10, ":var_43_localvariable"),
									(assign, ":value_10", 0),
									(assign, ":value_11", ":var_43"),
									(val_add, ":value_11", 1),
									(assign, ":value_12", ":localvariable"),
									(val_add, ":value_12", 1),
									(assign, ":value_9", 1),
								(try_end),
							(try_end),
						(try_end),
					(try_end),
					(store_random_in_range, ":random_in_range_0_7", 0, 8),
					(party_get_slot, ":value_3_retreat_flag", ":value_3", slot_party_retreat_flag),
					(assign, ":value_14", 0),
					(try_begin),
						(party_is_active, ":value_3_retreat_flag"),
						(assign, ":value_14", 1),
					(try_end),
					(try_begin),
						(eq, ":value_9", 0),
						(try_begin),
							(is_between, ":value_state", "p_pyongyang", "p_place_end"),
							(gt, ":value_2", 0),
							(eq, ":value_2", ":value_state"),
							(party_get_slot, ":value_2_town_alley", ":value_2", slot_town_alley),
							(party_stack_get_troop_id, ":party_stack_troop_id_value_3_0", ":value_3", 0),
							(try_begin),
								(neg|party_slot_eq, ":value_2", slot_town_tavern, ":party_stack_troop_id_value_3_0"),
								(val_div, ":value_2_town_alley", 2),
							(try_end),
							(call_script, "script_moral_level_diff", ":value_3", 1),
							(call_script, "script_train_level_diff", ":value_3", 1),
							(call_script, "script_party_army_size_execute", ":value_3", ":value_2_town_alley", 87),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
							(try_begin),
								(gt, ":party_size_wo_prisoners_value_2", 8000),
								(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
							(try_end),
							(call_script, "script_party_food_level_diff", ":value_3", 20000, 87),
							(party_set_slot, ":value_3", slot_town_prosperity, 0),
						(else_try),
							(eq, ":value_3_1", 2),
							(gt, ":var_25", 3000),
							(is_between, ":value_number_of_parties", "p_pyongyang", "p_place_end"),
							(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_number_of_parties"),
							(store_relation, ":relation_value_var_43", ":faction_of_party_g_encountered_party", ":value"),
							(lt, ":relation_value_var_43", 0),
							(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":value_number_of_parties"),
							(le, ":distance_to_party_from_party_value_3_var_43_localvariable", 2),
							(call_script, "script_party_count_fit_for_battle", ":value_3"),
							(assign, ":var_53", reg0),
							(call_script, "script_party_count_fit_for_battle", ":value_number_of_parties"),
							(assign, ":var_54", reg0),
							(try_begin),
								(gt, ":value_28", 0),
								(try_for_parties, ":var_55"),
									(neq, ":var_55", "p_main_party"),
									(neg|is_between, ":var_55", "p_temp_party", "p_reserved_5"),
									(neq, ":var_55", "p_reserved_5"),
									(party_is_active, ":var_55"),
									(party_slot_eq, ":var_55", slot_party_type, 1),
									(store_faction_of_party, ":faction_of_party_var_55", ":var_55"),
									(store_relation, ":relation_faction_of_party_g_encountered_party_faction_of_party_var_55", ":faction_of_party_g_encountered_party", ":faction_of_party_var_55"),
									(try_begin),
										(lt, ":relation_faction_of_party_g_encountered_party_faction_of_party_var_55", 0),
										(store_distance_to_party_from_party, ":distance_to_party_from_party_var_55_value_number_of_parties", ":var_55", ":value_number_of_parties"),
										(le, ":distance_to_party_from_party_var_55_value_number_of_parties", 6),
										(call_script, "script_party_count_fit_for_battle", ":var_55"),
										(val_add, ":var_53", reg0),
									(try_end),
									(try_begin),
										(ge, ":relation_faction_of_party_g_encountered_party_faction_of_party_var_55", 0),
										(store_distance_to_party_from_party, ":distance_to_party_from_party_var_55_value_number_of_parties", ":var_55", ":value_number_of_parties"),
										(le, ":distance_to_party_from_party_var_55_value_number_of_parties", 6),
										(call_script, "script_party_count_fit_for_battle", ":var_55"),
										(val_add, ":var_54", reg0),
									(try_end),
								(try_end),
							(else_try),
								(try_for_range, ":number", 56, 76),
									(faction_get_slot, ":value_number", ":value", ":number"),
									(ge, ":value_number", 0),
									(neg|is_between, ":value_number", "p_temp_party", "p_reserved_5"),
									(neq, ":value_number", "p_reserved_5"),
									(party_is_active, ":value_number"),
									(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_number", ":value_number_of_parties"),
									(le, ":distance_to_party_from_party_value_3_var_43_localvariable", 6),
									(call_script, "script_party_count_fit_for_battle", ":value_number"),
									(val_add, ":var_53", reg0),
								(try_end),
								(try_for_range, ":number", 56, 76),
									(faction_get_slot, ":faction_of_party_g_encountered_party_number", ":faction_of_party_g_encountered_party", ":number"),
									(ge, ":faction_of_party_g_encountered_party_number", 0),
									(neg|is_between, ":faction_of_party_g_encountered_party_number", "p_temp_party", "p_reserved_5"),
									(neq, ":faction_of_party_g_encountered_party_number", "p_reserved_5"),
									(party_is_active, ":faction_of_party_g_encountered_party_number"),
									(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":faction_of_party_g_encountered_party_number", ":value_number_of_parties"),
									(le, ":distance_to_party_from_party_value_3_var_43_localvariable", 6),
									(call_script, "script_party_count_fit_for_battle", ":faction_of_party_g_encountered_party_number"),
									(val_add, ":var_54", reg0),
								(try_end),
								(call_script, "script_party_count_fit_for_battle", ":value_number_of_parties"),
								(val_add, ":var_54", reg0),
							(try_end),
							(try_begin),
								(gt, ":var_53", ":var_54"),
								(call_script, "script_new_party_ai", ":value_3", 9, ":value_number_of_parties"),
							(else_try),
								(call_script, "script_new_party_ai", ":value_3", 0, ":value_number_of_parties"),
							(try_end),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(gt, ":value_2", 0),
							(ge, ":var_25", ":value_7"),
							(party_detach, ":value_3"),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_2"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(gt, ":value_2", 0),
							(party_get_slot, ":value_3_center_accumulated_rents", ":value_3", slot_center_accumulated_rents),
							(try_begin),
								(ge, ":value_3_center_accumulated_rents", 48),
								(heal_party, ":value_3"),
							(else_try),
								(val_add, ":value_3_center_accumulated_rents", 1),
								(party_set_slot, ":value_3", slot_center_accumulated_rents, ":value_3_center_accumulated_rents"),
							(try_end),
							(party_get_slot, ":value_2_town_alley", ":value_2", slot_town_alley),
							(party_stack_get_troop_id, ":party_stack_troop_id_value_3_0", ":value_3", 0),
							(try_begin),
								(neg|party_slot_eq, ":value_2", slot_town_tavern, ":party_stack_troop_id_value_3_0"),
								(val_div, ":value_2_town_alley", 2),
							(try_end),
							(call_script, "script_moral_level_diff", ":value_3", 1),
							(call_script, "script_train_level_diff", ":value_3", 1),
							(call_script, "script_party_army_size_execute", ":value_3", ":value_2_town_alley", 87),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
							(try_begin),
								(gt, ":party_size_wo_prisoners_value_2", 10000),
								(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
							(try_end),
							(call_script, "script_party_food_level_diff", ":value_3", 20000, 87),
							(party_set_slot, ":value_3", slot_town_prosperity, 0),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(this_or_next|eq, ":value_3_1", 6),
							(eq, ":value_3_1", 5),
							(is_between, ":value_3_retreat_flag", "p_pyongyang", "p_place_end"),
							(eq, ":value_14", 1),
							(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_3_retreat_flag"),
							(eq, ":faction_of_party_g_encountered_party", ":value"),
							(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":value_3_retreat_flag"),
							(le, ":distance_to_party_from_party_value_3_var_43_localvariable", 2),
							(party_set_slot, ":value_3", slot_center_accumulated_rents, 0),
							(party_attach_to_party, ":value_3", ":value_3_retreat_flag"),
							(call_script, "script_new_party_ai", ":value_3", 7, 0),
						(else_try),
							(gt, ":var_25", 6000),
							(eq, ":value_3_1", 6),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(le, ":var_25", 3000),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(is_between, ":value_state", "p_pyongyang", "p_place_end"),
							(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_state"),
							(store_relation, ":relation_value_faction_of_party_g_encountered_party", ":value", ":faction_of_party_g_encountered_party"),
							(ge, ":relation_value_faction_of_party_g_encountered_party", 0),
							(call_script, "script_new_party_ai", ":value_3", 5, ":value_state"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(is_between, ":value_number_of_parties", "p_pyongyang", "p_place_end"),
							(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_number_of_parties"),
							(store_relation, ":relation_value_var_43", ":faction_of_party_g_encountered_party", ":value"),
							(lt, ":relation_value_var_43", 0),
							(call_script, "script_new_party_ai", ":value_3", 2, ":value_number_of_parties"),
						(else_try),
							(eq, ":random_in_range_0_7", 0),
							(lt, ":battle_opponent_value_3", 0),
							(lt, ":var_25", 7000),
							(neq, ":value_3_1", 2),
							(neq, ":value_3_1", 5),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
						(else_try),
							(eq, ":value_3_1", 10),
							(lt, ":battle_opponent_value_3", 0),
							(eq, ":value_14", 1),
							(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":value_3_retreat_flag"),
							(gt, ":distance_to_party_from_party_value_3_var_43_localvariable", "$encount_dist"),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 8, ":value_3_town_prison"),
						(else_try),
							(eq, ":value_3_1", 3),
							(eq, ":value_14", 1),
							(store_faction_of_party, ":faction_of_party_value_3_retreat_flag", ":value_3_retreat_flag"),
							(store_relation, ":relation_value_faction_of_party_g_encountered_party", ":value", ":faction_of_party_value_3_retreat_flag"),
							(ge, ":relation_value_faction_of_party_g_encountered_party", 0),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(eq, ":value_3_1", 3),
							(lt, ":battle_opponent_value_3", 0),
							(eq, ":value_14", 0),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(eq, ":value_3_1", 3),
							(lt, ":battle_opponent_value_3", 0),
							(eq, ":value_14", 1),
							(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":value_3_retreat_flag"),
							(gt, ":distance_to_party_from_party_value_3_var_43_localvariable", "$encount_dist"),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3"),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(le, "$wm_popup_menu_id", 0),
				(le, "$molda_start_map_conversation", 0),
				(assign, ":value_15", 0),
				(try_begin),
					(neq, "$hourr_count", 19),
					(try_begin),
						(lt, "$main_q_step", 1),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 3),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 19),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 1),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 25),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 2),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 26),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 28),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 3),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 33),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 4),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 37),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 38),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 42),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 5),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 45),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 6),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 49),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 7),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 51),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 56),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 8),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 57),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 61),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 66),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 9),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 69),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 70),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 71),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 10),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 72),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 76),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 11),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 81),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 12),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 87),
						(is_between, "$main_q_troop", "trp_tt_lord_01_00", "trp_tt_lord_end"),
						(is_between, "$main_q_faction", "trp_tt_lord_01_00", "trp_tt_lord_end"),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 93),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 13),
						(assign, ":value_15", 1),
					(try_end),
					(try_begin),
						(eq, ":value_15", 1),
						(party_get_current_terrain, ":current_terrain_main_party", "p_main_party"),
						(this_or_next|eq, ":current_terrain_main_party", 7),
						(eq, ":current_terrain_main_party", 2),
						(assign, ":value_15", 0),
					(try_end),
				(try_end),
				(try_begin),
					(neq, "$hourr_count", 19),
					(eq, ":value_15", 1),
					(jump_to_menu, "mnu_main_quest_menu"),
				(else_try),
					(gt, "$need_meeting_loose", 0),
					(eq, "$meeting_popup_auto", 1),
					(neq, "$hourr_count", 19),
					(call_script, "script_attend_to_national_conference"),
				(else_try),
					(neq, "$hourr_count", 19),
					(store_random_in_range, ":random_in_range_0_2000", 0, 2000),
					(eq, ":random_in_range_0_2000", 0),
					(call_script, "script_wm_random_event_in_move"),
				(else_try),
					(eq, "$hourr_count", 19),
					(try_begin),
						(eq, "$dark_quest_we_know", 2),
						(jump_to_menu, "mnu_we_know_assassination"),
						(assign, "$dark_quest_we_know", 0),
					(else_try),
						(eq, "$dark_quest_we_know", 1),
						(jump_to_menu, "mnu_mess_we_know"),
						(assign, "$dark_quest_we_know", 2),
					(else_try),
						(eq, "$dayy_count", 6),
						(eq, "$pirate_king", 0),
						(assign, ":var_67", 0),
						(try_for_range, ":troop", "trp_ex_npc_020", "trp_ex_npc_054"),
							(troop_get_slot, ":troop_last_persuasion_time", ":troop", slot_troop_last_persuasion_time),
							(val_add, ":var_67", ":troop_last_persuasion_time"),
						(try_end),
						(try_begin),
							(ge, ":var_67", 87),
							(assign, "$pirate_king", 1),
							(jump_to_menu, "mnu_pirate_king"),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(call_script, "script_wm_map_icon_change_trig", "p_main_party"),
			(assign, ":value_3", "p_main_party"),
			(assign, ":var_70", 5000),
			(try_begin),
				(try_begin),
					(eq, "$r_player_class", 5),
					(party_set_slot, "p_main_party", slot_center_last_visited_by_lord, 0),
				(else_try),
					(eq, "$r_player_class", 3),
					(party_set_slot, "p_main_party", slot_village_smoke_added, 0),
				(try_end),
				(val_div, ":var_70", 5),
				(store_add, ":value_17", 42, 1),
				(try_for_range, ":localvariable_2", 30, ":value_17"),
					(party_get_slot, ":value_3_localvariable_2", ":value_3", ":localvariable_2"),
					(try_begin),
						(gt, ":value_3_localvariable_2", ":var_70"),
						(party_set_slot, ":value_3", ":localvariable_2", ":var_70"),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$r_player_class", 5),
				(party_set_slot, "p_main_party", slot_center_last_visited_by_lord, 1000),
			(else_try),
				(eq, "$r_player_class", 3),
				(party_set_slot, "p_main_party", slot_village_smoke_added, 1000),
			(try_end)
		]),

			(4.0, #13 for performance 4 default
		[
			(party_get_current_terrain, ":current_terrain_main_party", "p_main_party"),
			(try_begin),
				(this_or_next|eq, ":current_terrain_main_party", 4),
				(eq, ":current_terrain_main_party", 12),
				(assign, "$tom_sand_storm_chance", 20),
				(set_global_haze_amount, 0),
				(store_random_in_range, ":random_in_range_25_101", 25, 101),
				(set_global_cloud_amount, ":random_in_range_25_101"),
			(else_try),
				(this_or_next|eq, ":current_terrain_main_party", 3),
				(eq, ":current_terrain_main_party", 11),
				(assign, "$tom_sand_storm_chance", 15),
				(store_random_in_range, ":random_in_range_25_101", 0, 101),
				(set_global_haze_amount, ":random_in_range_25_101"),
				(store_random_in_range, ":random_in_range_25_101", 15, 100),
				(set_global_cloud_amount, ":random_in_range_25_101"),
			(else_try),
				(this_or_next|eq, ":current_terrain_main_party", 2),
				(eq, ":current_terrain_main_party", 10),
				(assign, "$tom_sand_storm_chance", 10),
				(store_random_in_range, ":random_in_range_25_101", 0, 50),
				(set_global_haze_amount, ":random_in_range_25_101"),
				(store_random_in_range, ":random_in_range_25_101", 0, 80),
				(set_global_cloud_amount, ":random_in_range_25_101"),
			(else_try),
				(this_or_next|eq, ":current_terrain_main_party", 5),
				(eq, ":current_terrain_main_party", 13),
				(assign, "$tom_sand_storm_chance", 25),
				(set_global_haze_amount, 0),
				(set_global_cloud_amount, 0),
			(else_try),
				(assign, "$tom_sand_storm_chance", 15),
				(store_random_in_range, ":random_in_range_25_101", 0, 101),
				(set_global_haze_amount, ":random_in_range_25_101"),
				(store_random_in_range, ":random_in_range_25_101", 0, 101),
				(set_global_cloud_amount, ":random_in_range_25_101"),
			(try_end)
		]),
		
		
		 #ramdon events chief
  ## Abhuva Random Events
   #---BEGIN LYX RANDOM EVENTS---
(21 * 24,[   # interval currently set to 6 hours for testing  - should be 14 * 24 for normal play, 1 * 6 for testing

   # Init
   # ---------------------------------------------------------------------------
#   (eq,"$random_events",1), ## abhuva, 1 = use random events, 0 = dont use them
   ##   (display_message, "@_Random Events Trigger fired.", 0xFF8000),  ## for bugfix



          #+freelancer chief #brytenwalda chief

            
       (assign, ":total_events", 11),   # update this when adding/removing events!
   (val_add, ":total_events", 1),   # MnB has weird ideas of ranges
   (store_random_in_range, ":curr_event", 0, ":total_events"),
   (neq, ":curr_event", "$g_lyx_last_random_event"),   # ignore event if same as last
   (assign, "$g_lyx_last_random_event", ":curr_event"),
   (assign, ":pos", 0),
   (try_begin), (eq,1,2),   # dummy


   # Events
   # ---------------------------------------------------------------------------

   # --- PLAYER INJURED --- 15
   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
#      (call_script, "script_get_troop_health", "trp_player"), (ge,reg0,60),   # abort if player is already weak
      (try_begin),
#       (eq,"$random_events_box",0),
       (display_message, "@During today's training, you were accidently injured. While the wounds aren't severe, it may take some time for them to heal."),
      (else_try),
           (dialog_box, "@During today's training, you were accidently injured. While the wounds aren't severe, it may take some time for them to heal.", "@Training accident:"),
     (try_end),
     #(call_script, "script_change_troop_health", "trp_player", -20),
  
   # --- PLAYER INJURED --- 16
   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
#      (call_script, "script_get_troop_health", "trp_player"), (ge,reg0,60),   # abort if player is already weak
      (try_begin),
#       (eq,"$random_events_box",0),
       (display_message, "@Today, you awoke with a horrible toothache and now you can no longer hide the pain."),
      (else_try),
           (dialog_box, "@Today, you awoke with a horrible toothache and now you can no longer hide the pain.", "@Toothache:"),
     (try_end),
     #(call_script, "script_change_troop_health", "trp_player", -5),

  # --- PLAYER INJURED --- 17
  (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
#      (call_script, "script_get_troop_health", "trp_player"), (ge,reg0,60),   # abort if player is already weak
     (try_begin),
#       (eq,"$random_events_box",0),
      (display_message, "@You slipped on wet ground, and you were injured."),
     (else_try),
          (dialog_box, "@You slipped on wet ground, and you were injured.", "@Injured."),
    (try_end),
    #(call_script, "script_change_troop_health", "trp_player", -5),

   # --- PLAYER INJURED --- 18
   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
#      (call_script, "script_get_troop_health", "trp_player"), (ge,reg0,60),   # abort if player is already weak
      (try_begin),
#       (eq,"$random_events_box",0),
       (display_message, "@(While travelling) You happen to find an abandoned house. You found some loot."),
      (else_try),
           (dialog_box, "@(While travelling) You happen to find an abandoned house. You found some loot.", "@Abandoned house."),
     (try_end),
     #(troop_add_gold, "trp_player", 50),
	#(troop_add_item, "trp_player", "itm_sword_type_xii", 0), #chief cambiado premio por eliminar al borracho
	#(troop_add_item, "trp_player", "itm_smoked_fish", 0), #chief cambiado premio por eliminar al borracho


   # --- PLAYER strong ---19
##   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
#      (call_script, "script_get_troop_health", "trp_player"), (ge,reg0,60),   # abort if player is already weak
##     (try_begin),
#       (eq,"$random_events_box",0),
##       (display_message, "@The adventure, life in the field, the constant training makes you feel strong and well, you are ready to face any challenge."),
##     (else_try),
##      (dialog_box, "@The adventure, life in the field, the constant training makes you feel strong and well, you are ready to face any challenge.", "@Heal improved:"),
##    (try_end),
##      #(call_script, "script_change_troop_health", "trp_player", 40),
# = Two ## means that that part was not commented, one # means that part was commented and should not be uncommented if you want to use this feature again.
	    
	  
   # --- GOLD FOUND --- 20
   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
      (try_begin),
#       (eq,"$random_events_box",0),
       (display_message, "@Today you got lucky and found a small bag hidden behind a bush. Inside the bag was 300 denars."),
      (else_try),
          (dialog_box, "@Today you got lucky and found a small bag hidden behind a bush. Inside the bag was 300 denars.", "@Found Gold bag:"),
     (try_end),
     #(troop_add_gold, "trp_player", 300),

  # --- WORTHLESS METAL FOUND --- 21
   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
      (try_begin),
#       (eq,"$random_events_box",0),
       (display_message, "@During a small rest you noticed a shiny object in the ground caught your eye. You took a closer look, thinking it may be some denars. Unfortunately it was only a small piece of rusted metal lying on the ground, totally worthless."),
       (else_try),
           (dialog_box, "@During a small rest you noticed a shiny object in the ground caught your eye. You took a closer look, thinking it may be some denars. Unfortunately it was only a small piece of rusted metal lying on the ground, totally worthless.", "@Found some crap:"),
      (try_end),

  # --- Reservas de agua contaminadas --- 22
   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
      (try_begin),
#       (eq,"$random_events_box",0),
       (display_message, "@The water reserves have been contaminated and it must be rationed until you reach the next town."),
       (else_try),
           (dialog_box, "@The water reserves have been contaminated and it must be rationed until you reach the next town.", "@Water Reserves contaminated."),
      (try_end),
     #(call_script, "script_change_troop_health", "trp_player", -15),
     #(call_script, "script_change_player_party_morale", -15),
   
  # --- Encuentra cargamento de hidromiel --- 23
   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
      (try_begin),
#       (eq,"$random_events_box",0),
       (display_message, "@You and your party have come across an abandoned wagon of full of mead, and you gift it to your men."),
       (else_try),
           (dialog_box, "@You and your party have come across an abandoned wagon of full of mead, and you gift it to your men.", "@Wagon of Mead."),
      (try_end),
     #(call_script, "script_change_player_party_morale", 10),
      
  # --- leales regalan a la party del heroe --- 24
   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
      (try_begin),
#       (eq,"$random_events_box",0),
       (display_message, "@Loyalist supporters from a nearby village have gathered a bounty of food for your troops."),
       (else_try),
           (dialog_box, "@Loyalist supporters from a nearby village have gathered a bounty of food for your troops.", "@Bounty of food."),
      (try_end),
     #(call_script, "script_change_player_party_morale", 10),

## # --- PLAYER INJURED/GOLD LOSS --- 25  needs editing
##   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
##      (call_script, "script_get_troop_health", "trp_player"), (ge,reg0,40),   # abort if player is already weak
##      #(call_script, "script_get_player_gold", "trp_player"), (ge, reg0, 120), # abort if too less money left on player
##      (try_begin),
##       (eq,"$random_events_box",0),
##       (display_message, "@Today you were injured by stumbling across a hidden stone. Your wounds are minor but later you discovered that you have lossed a bag of denar during the incident. DEBUG MESSAGE: Needs editing"),
##      (else_try),
##             (dialog_box, "@Today you were injured by stumbling across a hidden stone. Your wounds are minor but later you discovered that you have lossed a bag of denar during the incident.", "@Minor accident:"),
##     (try_end),
##     #(call_script, "script_change_troop_health", "trp_player", -25),
##     ##(troop_add_gold, "trp_player", -120),

#Griggs additional events
  # --- BATTLE LEFTOVERS --- 25  
   (else_try),   (val_add,":pos",1), (eq,":pos",":curr_event"),   # this first line is same for all events
      (try_begin),
#       (eq,"$random_events_box",0),
       (display_message, "@You have found leftovers of a recent battle. Searching the bodies, you managed to find 200 denars."),
      (else_try),
             (dialog_box, "@You have found leftovers of a recent battle. Searching the bodies, you managed to find 200 denars.", "@Minor accident:"),
     (try_end),
     #(troop_add_gold, "trp_player", 200),
#Griggs additional events end
     # Closing
   # --------------------------------------
   ## ideas for future events: morale of troops +/-, adding inventory items (food, maybe armour etc with smaller chance)
   (try_end),
] ),
#---END LYX RANDOM EVENTS---
## Abhuva Random Events ends chief acaba
      #x############################################
# EVENTS WITHOUT PREQUISITES ARE SPAWNED BY THIS TRIGGER 
#x############################################ 
#Works
(882, #Everything 1.5xed.
	[
          #+freelancer chief #brytenwalda chief




#(neg|troop_slot_ge, "trp_player", slot_troop_prisoner_of_party, 0),
        #(troop_get_slot, ":player_renown", "trp_player", slot_troop_renown),
        #(gt, ":player_renown", 270),
          (store_random_in_range, ":rand", 0, 13),
                                          (try_begin),
                                            (eq, ":rand", 0), 
			(jump_to_menu,"mnu_event_01"),
                                          (else_try),
                                            (eq, ":rand", 1),
			(jump_to_menu,"mnu_event_23"),
                                          (else_try),
                                            (eq, ":rand", 2),
			(jump_to_menu,"mnu_event_24"),
                                          (else_try),
                                            (eq, ":rand", 3),
			(jump_to_menu,"mnu_event_26"),
                                          (else_try),
                                            (eq, ":rand", 4),
                        (jump_to_menu,"mnu_event_02"),
                                           (else_try),
                                            (eq, ":rand", 5),
                        (jump_to_menu,"mnu_event_03"),
                                          (else_try),
                                            (eq, ":rand", 6),
                        (jump_to_menu,"mnu_event_05"),
                                          (else_try),
                                            (eq, ":rand", 7),
                        (jump_to_menu,"mnu_event_07"),
                                          (else_try),
						(display_message,"@ "),
					(try_end),
					]),

(1230,
	[
          #+freelancer chief #brytenwalda chief




#(neg|troop_slot_ge, "trp_player", slot_troop_prisoner_of_party, 0),
        #(troop_get_slot, ":player_renown", "trp_player", slot_troop_renown),
        #(gt, ":player_renown", 140),
          (store_random_in_range, ":rand", 0, 15),
                                          (try_begin),
                                            (eq, ":rand", 0), 
			(jump_to_menu,"mnu_event_04"),
                                          (else_try),
                                            (eq, ":rand", 1),
			(jump_to_menu,"mnu_event_11"),
                                          (else_try),
                                            (eq, ":rand", 2),
			(jump_to_menu,"mnu_event_27"),
        #                                  (else_try),
        #                                    (eq, ":rand", 3),
		#	(jump_to_menu,"mnu_event_28"),
                                          (else_try),
                                            (eq, ":rand", 4),
                        (jump_to_menu,"mnu_event_12"),
                                           (else_try),
                                            (eq, ":rand", 5),
                        (jump_to_menu,"mnu_event_13"),
                                          (else_try),
                                            (eq, ":rand", 6),
                        (jump_to_menu,"mnu_event_14"),
                                          (else_try),
                                            (eq, ":rand", 7),
                        (jump_to_menu,"mnu_event_101"),
                                          (else_try),
                                            (eq, ":rand", 8),
                        (jump_to_menu,"mnu_event_102"),
                                          (else_try),
                                            (eq, ":rand", 9),
                        (jump_to_menu,"mnu_event_103"),
                                          (else_try),
        (display_message,"@ "),
          (try_end),
	]),

(1152,
	[
          #+freelancer chief #brytenwalda chief




#(neg|troop_slot_ge, "trp_player", slot_troop_prisoner_of_party, 0),
        #(troop_get_slot, ":player_renown", "trp_player", slot_troop_renown),
        #(gt, ":player_renown", 300),
          (store_random_in_range, ":rand", 0, 12),
                                          (try_begin),
                                            (eq, ":rand", 0), 
			(jump_to_menu,"mnu_event_29"),
                                          (else_try),
                                            (eq, ":rand", 1),
			(jump_to_menu,"mnu_event_30"),
                                          (else_try),
                                            (eq, ":rand", 2),
			(jump_to_menu,"mnu_event_31"),
                                          (else_try),
                                            (eq, ":rand", 3),
			(jump_to_menu,"mnu_event_36"),
                                          (else_try),
                                            (eq, ":rand", 4),
			(jump_to_menu,"mnu_event_37"),
                                           (else_try),
                                            (eq, ":rand", 5),
			(jump_to_menu,"mnu_event_32"),
                                          (else_try),
                                            (eq, ":rand", 6),
			(jump_to_menu,"mnu_event_33"),
                                          (else_try),
                                            (eq, ":rand", 7),
			(jump_to_menu,"mnu_event_34"),
                                          (else_try),
        (display_message,"@ "),
          (try_end),
	]),

    (1080,
	[

          #+freelancer chief #brytenwalda chief
   (assign, ":has_fief1", 0),
    (try_for_range, ":party", "p_pyongyang", "p_place_end"),
      (party_get_slot,  ":lord_troop_id", ":party", slot_town_lord),
      (eq, ":lord_troop_id", "trp_player"),
      (assign, ":has_fief1", 1),
    (try_end),
    (eq, ":has_fief1", 1),





	#(neg|troop_slot_ge, "trp_player", slot_troop_prisoner_of_party, 0),
        #(troop_get_slot, ":player_renown", "trp_player", slot_troop_renown),
        #(gt, ":player_renown", 140),
          (store_random_in_range, ":rand", 0, 10),
                                          (try_begin),
                                            (eq, ":rand", 0), 
			(jump_to_menu,"mnu_event_06"),
                                          (else_try),
                                            (eq, ":rand", 1),
			(jump_to_menu,"mnu_event_08"),
                                          (else_try),
                                            (eq, ":rand", 2),
			(jump_to_menu,"mnu_event_18"),
                                          (else_try),
                                            (eq, ":rand", 3),
			(jump_to_menu,"mnu_event_19"),
                                          (else_try),
                                            (eq, ":rand", 4),
			(jump_to_menu,"mnu_event_22"),
                                          (else_try),
        (display_message,"@ "),
          (try_end),
	]),

(972,
	[
          #+freelancer chief #brytenwalda chief




#(neg|troop_slot_ge, "trp_player", slot_troop_prisoner_of_party, 0),
        #(troop_get_slot, ":player_renown", "trp_player", slot_troop_renown),
        #(gt, ":player_renown", 220),
          (store_random_in_range, ":rand", 0, 12),
                                          (try_begin),
                                            (eq, ":rand", 0), 
			(jump_to_menu,"mnu_event_35"),
                                          (else_try),
                                            (eq, ":rand", 1),
			(jump_to_menu,"mnu_event_37"),
                                          (else_try),
                                            (eq, ":rand", 2),
			(jump_to_menu,"mnu_event_40"),
                                           (else_try),
                                            (eq, ":rand", 3),
			(jump_to_menu,"mnu_event_42"),
                                          (else_try),
                                            (eq, ":rand", 4),
			(jump_to_menu,"mnu_event_41"),
                                          (else_try),
        (display_message,"@ "),
          (try_end),
	]),

  (810,
	[
          #+freelancer chief #brytenwalda chief




	#(neg|troop_slot_ge, "trp_player", slot_troop_prisoner_of_party, 0),
          (store_random_in_range, ":rand", 0, 13),
                                          (try_begin),
                                            (eq, ":rand", 0), 
			(jump_to_menu,"mnu_event_10"),
                                          (else_try),
                                            (eq, ":rand", 1),
			(jump_to_menu,"mnu_event_09"), #Good
                                          (else_try),
                                            (eq, ":rand", 2),
			(jump_to_menu,"mnu_event_25"),
                                          (else_try),
                                            (eq, ":rand", 3),
			(jump_to_menu,"mnu_event_15"),
                                          (else_try),
                                            (eq, ":rand", 4),
			(jump_to_menu,"mnu_event_16"),
                                           (else_try),
                                            (eq, ":rand", 5),
			(jump_to_menu,"mnu_event_20"),
                                          (else_try),
                                            (eq, ":rand", 6),
			(jump_to_menu,"mnu_event_21"),
                                          (else_try),
                                            (eq, ":rand", 7),
			(jump_to_menu,"mnu_event_17"), #Works
                                          (else_try),
        (display_message,"@ "),
          (try_end),
	]),

  #Random events
  (1244,
	[
   (assign, ":has_fief1", 0),
    (try_for_range, ":party", "p_pyongyang", "p_place_end"),
      (party_get_slot,  ":lord_troop_id", ":party", slot_town_lord),
      (eq, ":lord_troop_id", "trp_player"),
      (assign, ":has_fief1", 1),
    (try_end),
    (eq, ":has_fief1", 1),




#(neg|troop_slot_ge, "trp_player", slot_troop_prisoner_of_party, 0),
        #(troop_get_slot, ":player_renown", "trp_player", slot_troop_renown),
        #(gt, ":player_renown", 180),
                                          (try_begin),
                                            (eq, "$g_juicio", 0), 
			(jump_to_menu,"mnu_event_01_juicio"),
                                            (assign, "$g_juicio", 1), 
                                          (else_try),
                                            (eq, "$g_juicio", 1), 
			(jump_to_menu,"mnu_event_02_juicio"),
                                            (assign, "$g_juicio", 2), 
                                          (else_try),
                                            (eq, "$g_juicio", 2), 
			(jump_to_menu,"mnu_event_03_juicio"),
                                            (assign, "$g_juicio", 3), 
                                          (else_try),
                                            (eq, "$g_juicio", 3), 
			(jump_to_menu,"mnu_event_04_juicio"),
                                            (assign, "$g_juicio", 4), 
                                          (else_try),
                                            (eq, "$g_juicio", 4), 
			(jump_to_menu,"mnu_event_06_juicio"),
                                            (assign, "$g_juicio", 5), 
                                           (else_try),
                                            (eq, "$g_juicio", 5), 
			(jump_to_menu,"mnu_event_07_juicio"),
                                            (assign, "$g_juicio", 6), 
                                          (else_try),
                                            (eq, "$g_juicio", 6), 
			(jump_to_menu,"mnu_event_08_juicio"),
                                            (assign, "$g_juicio", 7), 
                                          (else_try),
                                            (eq, "$g_juicio", 7), 
			(jump_to_menu,"mnu_event_09_juicio"),
                                            (assign, "$g_juicio", 8), 
                                          (else_try),
                                            (eq, "$g_juicio", 8), 
			(jump_to_menu,"mnu_event_11_juicio"),
                                            (assign, "$g_juicio", 9), 
                                          (else_try),
                                            (eq, "$g_juicio", 9), 
			(jump_to_menu,"mnu_event_12_juicio"),
                                            (assign, "$g_juicio", 10), 
                                          (else_try),
                                            (eq, "$g_juicio", 10), 
			(jump_to_menu,"mnu_event_13_juicio"),
                                            (assign, "$g_juicio", 11), 
                                          (else_try),
                                            (eq, "$g_juicio", 11), 
			(jump_to_menu,"mnu_event_14_juicio"),
                                            (assign, "$g_juicio", 12), 
                                           (else_try),
                                            (eq, "$g_juicio", 12), 
			(jump_to_menu,"mnu_event_15_juicio"),
                                            (assign, "$g_juicio", 13), 
                                          (else_try),
                                            (eq, "$g_juicio", 13), 
			(jump_to_menu,"mnu_event_16_juicio"),
                                            (assign, "$g_juicio", 14), 
                                          (else_try),
                                            (eq, "$g_juicio", 14), 
			(jump_to_menu,"mnu_event_17_juicio"),
                                            (assign, "$g_juicio", 15), 
                                          (else_try),
                                            (eq, "$g_juicio", 15), 
			(jump_to_menu,"mnu_event_18_juicio"),
                                            (assign, "$g_juicio", 16), 
                                          (else_try),
                                            (eq, "$g_juicio", 16), 
			(jump_to_menu,"mnu_event_19_juicio"),
                                            (assign, "$g_juicio", 17), 
                                          (else_try),
                                            (eq, "$g_juicio", 18), 
			(jump_to_menu,"mnu_event_21_juicio"),
                                            (assign, "$g_juicio", 19), 
                                           (else_try),
                                            (eq, "$g_juicio", 19), 
			(jump_to_menu,"mnu_event_22_juicio"),
                                            (assign, "$g_juicio", 20), 
                                          (else_try),
                                            (eq, "$g_juicio", 20), 
			(jump_to_menu,"mnu_event_23_juicio"),
                                            (assign, "$g_juicio", 21), 
                                          (else_try),
                                            (eq, "$g_juicio", 21), 
			(jump_to_menu,"mnu_event_24_juicio"),
                                            (assign, "$g_juicio", 22), 
                                          (else_try),
                                            (eq, "$g_juicio", 22), 
			(jump_to_menu,"mnu_event_05_juicio"),
                                            (assign, "$g_juicio", 23), 
                                          (else_try),
        #(display_message,"@ "),
          (try_end),
	]),
		
		
]