from header_common import *
from header_operations import *
from header_parties import *
from header_items import *
from header_skills import *
from header_triggers import *
from header_troops import *

from module_constants import *

####################################################################################################################
#  Each trigger contains the following fields:
# 1) Check interval: How frequently this trigger will be checked
# 2) Delay interval: Time to wait before applying the consequences of the trigger
#    After its conditions have been evaluated as true.
# 3) Re-arm interval. How much time must pass after applying the consequences of the trigger for the trigger to become active again.
#    You can put the constant ti_once here to make sure that the trigger never becomes active again after it fires once.
# 4) Conditions block (list). This must be a valid operation block. See header_operations.py for reference.
#    Every time the trigger is checked, the conditions block will be executed.
#    If the conditions block returns true, the consequences block will be executed.
#    If the conditions block is empty, it is assumed that it always evaluates to true.
# 5) Consequences block (list). This must be a valid operation block. See header_operations.py for reference. 
####################################################################################################################

# Some constants for use below
merchant_inventory_space = 30
num_merchandise_goods = 36



triggers = [
	(0.0, 0.0, 720.0,
		[],

		[
		(try_begin),
		(eq, "$guide", 1),
		(assign, "$guide", 0),
		(jump_to_menu, "mnu_notes_and_hotkeys_full"),
		(try_end),
		
			(try_begin),
				(ge, "$month_count", 12),
				(assign, "$month_count", 1),
				(val_add, "$year_count", 1),
			(else_try),
				(val_add, "$month_count", 1),
			(try_end),
			(try_begin),
				(eq, "$month_count", 6),
				(call_script, "script_world_map_res_slot_sett"),
			(try_end),
			(call_script, "script_troop_real_class_slot_sett_try_for", "trp_townsman", "trp_tournament_master"),
			(call_script, "script_place_upgrade_slot_sett"),
			(store_faction_of_troop, ":faction_of_troop_tt_lord_17_00", "trp_tt_lord_17_00"),
			(try_begin),
				(store_faction_of_troop, ":faction_of_troop_tt_lord_17_01", "trp_tt_lord_17_01"),
				(neq, ":faction_of_troop_tt_lord_17_01", ":faction_of_troop_tt_lord_17_00"),
				(call_script, "script_lord_faction_to", "trp_tt_lord_17_01", ":faction_of_troop_tt_lord_17_00"),
			(try_end),
			(try_begin),
				(store_faction_of_troop, ":faction_of_troop_tt_lord_17_01", "trp_tt_lord_17_02"),
				(neq, ":faction_of_troop_tt_lord_17_01", ":faction_of_troop_tt_lord_17_00"),
				(call_script, "script_lord_faction_to", "trp_tt_lord_17_02", ":faction_of_troop_tt_lord_17_00"),
			(try_end),
			(try_begin),
				(gt, "$year_count", 1),
				(eq, "$month_count", 11),
				(store_faction_of_troop, ":faction_of_troop_tt_lord_17_00", "trp_tt_lord_17_00"),
				(try_begin),
					(store_faction_of_troop, ":faction_of_troop_tt_lord_17_01", "trp_tt_lord_39_07"),
					(neq, ":faction_of_troop_tt_lord_17_01", ":faction_of_troop_tt_lord_17_00"),
					(faction_slot_eq, ":faction_of_troop_tt_lord_17_00", 1, "trp_tt_lord_17_00"),
					(call_script, "script_lord_faction_to", "trp_tt_lord_39_07", ":faction_of_troop_tt_lord_17_00"),
				(try_end),
			(try_end),
			(try_begin),
				(gt, "$year_count", 4),
				(eq, "$month_count", 3),
				(try_begin),
					(store_faction_of_party, ":faction_of_party_xinye", "p_xinye"),
					(eq, ":faction_of_party_xinye", ":faction_of_troop_tt_lord_17_00"),
					(store_faction_of_troop, ":faction_of_troop_tt_lord_17_01", "trp_tt_ex_lord_01"),
					(neq, ":faction_of_troop_tt_lord_17_01", ":faction_of_troop_tt_lord_17_00"),
					(faction_slot_eq, ":faction_of_troop_tt_lord_17_00", 1, "trp_tt_lord_17_00"),
					(troop_set_slot, "trp_tt_ex_lord_01", slot_troop_renown, 1),
					(call_script, "script_lord_faction_to", "trp_tt_ex_lord_01", ":faction_of_troop_tt_lord_17_00"),
				(try_end),
			(try_end),
			(assign, ":faction_of_troop_tt_lord_17_00", "fac_kingdom_20"),
			(try_begin),
				(eq, "$start_age", 1573),
				(gt, "$year_count", 8),
				(eq, "$month_count", 3),
				(try_begin),
					(store_faction_of_troop, ":faction_of_troop_tt_lord_17_01", "trp_tt_lord_20_05"),
					(neq, ":faction_of_troop_tt_lord_17_01", ":faction_of_troop_tt_lord_17_00"),
					(faction_slot_eq, ":faction_of_troop_tt_lord_17_00", 1, "trp_tt_lord_20_08"),
					(troop_set_slot, "trp_tt_lord_20_05", slot_troop_renown, 1),
					(call_script, "script_lord_faction_to", "trp_tt_lord_20_05", ":faction_of_troop_tt_lord_17_00"),
				(try_end),
			(try_end),
			(try_begin),
				(gt, "$year_count", 2),
				(eq, "$month_count", 3),
				(store_faction_of_troop, ":faction_of_troop_tt_lord_17_00", "trp_tt_lord_30_00"),
				(store_faction_of_party, ":faction_of_party_xinye", "p_gorgonac"),
				(try_begin),
					(eq, ":faction_of_party_xinye", ":faction_of_troop_tt_lord_17_00"),
					(store_faction_of_troop, ":faction_of_troop_tt_lord_17_01", "trp_tt_lord_21_01"),
					(neq, ":faction_of_troop_tt_lord_17_01", ":faction_of_troop_tt_lord_17_00"),
					(faction_slot_eq, ":faction_of_troop_tt_lord_17_00", 1, "trp_tt_lord_30_00"),
					(call_script, "script_lord_faction_to", "trp_tt_lord_21_01", ":faction_of_troop_tt_lord_17_00"),
				(try_end),
				(try_begin),
					(eq, ":faction_of_party_xinye", ":faction_of_troop_tt_lord_17_00"),
					(store_faction_of_troop, ":faction_of_troop_tt_lord_17_01", "trp_tt_lord_21_02"),
					(neq, ":faction_of_troop_tt_lord_17_01", ":faction_of_troop_tt_lord_17_00"),
					(faction_slot_eq, ":faction_of_troop_tt_lord_17_00", 1, "trp_tt_lord_30_00"),
					(call_script, "script_lord_faction_to", "trp_tt_lord_21_02", ":faction_of_troop_tt_lord_17_00"),
				(try_end),
			(try_end),
			(try_begin),
				(gt, "$convert_possi", 0),
				(val_sub, "$convert_possi", 1),
			(try_end),
			(try_begin),
				(troop_get_slot, ":player_23", "trp_player", 23),
				(assign, ":value", 0),
				(try_for_range, ":troop", "trp_tt_lord_01_00", "trp_tt_lord_end"),
					(troop_slot_eq, ":troop", slot_troop_renown, 1),
					(troop_get_slot, ":troop_occupation", ":troop", slot_troop_occupation),
					(troop_get_slot, ":troop_23", ":troop", 23),
					(troop_get_slot, ":troop_leaded_party", ":troop", slot_troop_leaded_party),
					(try_begin),
						(gt, ":troop_leaded_party", 0),
						(val_sub, ":troop_leaded_party", 1),
						(troop_set_slot, ":troop", slot_troop_leaded_party, ":troop_leaded_party"),
					(try_end),
					(try_begin),
						(neq, ":player_23", ":troop_23"),
						(gt, ":troop_occupation", 45),
						(val_sub, ":troop_occupation", 2),
						(assign, ":value", 1),
					(else_try),
						(gt, ":troop_occupation", 75),
						(val_sub, ":troop_occupation", 1),
					(try_end),
					(troop_set_slot, ":troop", slot_troop_occupation, ":troop_occupation"),
				(try_end),
				(try_for_range, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_get_slot, ":troop_occupation", ":troop", slot_troop_occupation),
					(troop_get_slot, ":troop_23", ":troop", 23),
					(try_begin),
						(neq, ":player_23", ":troop_23"),
						(gt, ":troop_occupation", 45),
						(val_sub, ":troop_occupation", 2),
						(assign, ":value", 1),
					(else_try),
						(gt, ":troop_occupation", 75),
						(val_sub, ":troop_occupation", 1),
					(try_end),
					(troop_set_slot, ":troop", slot_troop_occupation, ":troop_occupation"),
				(try_end),
				(try_begin),
					(eq, ":value", 1),
					(display_message, "str_reli_relation_minus2", 0x00ffff00),
					(display_message, "str_reli_relation_minus1", 0x00ffff00),
				(try_end),
			(try_end),
			(try_begin),
				(try_for_range, ":troop_2", "trp_npc1", "trp_kingdom_1_lord"),
					(call_script, "script_wm_main_party_has_troop_sc", ":troop_2"),
					(eq, "$wm_comp_continue", 1),
					(try_begin),
						(neg|troop_slot_ge, "trp_player", 13, 25),
						(this_or_next|eq, ":troop_2", "trp_npc1"),
						(this_or_next|eq, ":troop_2", "trp_npc2"),
						(this_or_next|eq, ":troop_2", "trp_npc3"),
						(this_or_next|eq, ":troop_2", "trp_npc4"),
						(this_or_next|eq, ":troop_2", "trp_tt_lady_ex_07"),
						(this_or_next|eq, ":troop_2", "trp_npc_21"),
						(eq, ":troop_2", "trp_npc_23"),
						(call_script, "script_wm_comp_separate", ":troop_2"),
					(try_end),
				(try_end),
				(try_for_range, ":troop_2", "trp_tt_lady_ex_01", "trp_tt_lady_ex_18"),
					(call_script, "script_wm_main_party_has_troop_sc", ":troop_2"),
					(eq, "$wm_comp_continue", 1),
					(try_begin),
						(neg|troop_slot_ge, "trp_player", 13, 25),
						(this_or_next|eq, ":troop_2", "trp_npc1"),
						(this_or_next|eq, ":troop_2", "trp_npc2"),
						(this_or_next|eq, ":troop_2", "trp_npc3"),
						(this_or_next|eq, ":troop_2", "trp_npc4"),
						(this_or_next|eq, ":troop_2", "trp_tt_lady_ex_07"),
						(this_or_next|eq, ":troop_2", "trp_npc_21"),
						(eq, ":troop_2", "trp_npc_23"),
						(call_script, "script_wm_comp_separate", ":troop_2"),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(gt, "$debt_date_month", 0),
				(call_script, "script_party_money_level_ge", "p_main_party", "$ply_debt_per_month"),
				(eq, "$wm_mo_continue", 1),
				(call_script, "script_party_money_level_dif_no_mes", "p_main_party", "$ply_debt_per_month", 34),
				(assign, reg8, "$ply_debt_per_month"),
				(display_message, "str_paying_debt_reg8"),
				(val_sub, "$debt_date_month", 1),
				(assign, reg8, "$debt_date_month"),
				(display_message, "str_debt_remain_reg8"),
			(try_end),
			(call_script, "script_pirate_spawn_sett"),
			(try_begin),
				(troop_get_slot, ":player_state", "trp_player", slot_troop_state),
				(gt, ":player_state", 0),
				(troop_get_slot, ":player_state_state", ":player_state", slot_troop_state),
				(neq, "trp_player", ":player_state_state"),
				(troop_set_slot, "trp_player", slot_troop_state, 0),
			(try_end),
			(try_for_range, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
				(troop_get_slot, ":player_state", ":troop", slot_troop_state),
				(gt, ":player_state", 0),
				(troop_get_slot, ":player_state_state", ":player_state", slot_troop_state),
				(gt, ":player_state_state", 0),
				(neq, ":troop", ":player_state_state"),
				(troop_set_slot, ":troop", slot_troop_state, 0),
			(try_end),
			(try_for_range, ":troop", "trp_tt_lord_01_00", "trp_tt_lord_end"),
				(troop_get_slot, ":player_state", ":troop", slot_troop_state),
				(gt, ":player_state", 0),
				(troop_get_slot, ":player_state_state", ":player_state", slot_troop_state),
				(gt, ":player_state_state", 0),
				(neq, ":troop", ":player_state_state"),
				(troop_set_slot, ":troop", slot_troop_state, 0),
			(try_end),
			(assign, ":value_2", 0),
			(troop_get_slot, ":player_42", "trp_player", 42),
			(try_begin),
				(neq, ":player_42", "p_main_party"),
				(neg|is_between, ":player_42", "p_temp_party", "p_reserved_5"),
				(neq, ":player_42", "p_reserved_5"),
				(party_is_active, ":player_42"),
				(party_slot_eq, ":player_42", slot_party_type, 5),
				(party_get_slot, ":player_42_town_wealth", ":player_42", slot_town_wealth),
				(assign, "$prev_revenue_caravan_1", ":player_42_town_wealth"),
				(val_add, ":value_2", ":player_42_town_wealth"),
				(party_set_slot, ":player_42", slot_town_wealth, 0),
				(try_begin),
					(gt, "$policy_trade_plan", 0),
					(le, "$policy_trade_plan", 5),
					(store_mul, ":value_3", "$policy_trade_plan", 200),
					(val_add, ":value_2", ":value_3"),
				(try_end),
			(else_try),
				(assign, "$prev_revenue_caravan_1", 0),
			(try_end),
			(troop_get_slot, ":player_42", "trp_player", 43),
			(try_begin),
				(neq, ":player_42", "p_main_party"),
				(neg|is_between, ":player_42", "p_temp_party", "p_reserved_5"),
				(neq, ":player_42", "p_reserved_5"),
				(party_is_active, ":player_42"),
				(party_slot_eq, ":player_42", slot_party_type, 5),
				(party_get_slot, ":player_42_town_wealth", ":player_42", slot_town_wealth),
				(assign, "$prev_revenue_caravan_2", ":player_42_town_wealth"),
				(val_add, ":value_2", ":player_42_town_wealth"),
				(party_set_slot, ":player_42", slot_town_wealth, 0),
				(try_begin),
					(gt, "$policy_trade_plan", 0),
					(le, "$policy_trade_plan", 5),
					(store_mul, ":value_3", "$policy_trade_plan", 200),
					(val_add, ":value_2", ":value_3"),
				(try_end),
			(else_try),
				(assign, "$prev_revenue_caravan_2", 0),
			(try_end),
			(try_begin),
				(gt, ":value_2", 0),
				(assign, reg8, ":value_2"),
				(display_message, "str_trader_revenue_sum", 0x00ff9000),
				(call_script, "script_party_money_level_diff", "p_main_party", ":value_2", 87),
			(try_end),
			(assign, "$brothel_prev_income", 0),
			(try_begin),
				(is_between, "$brothel_target_party", "p_pyongyang", "p_place_end"),
				(store_mul, ":value_2", 1000, -1),
				(assign, ":value_4", 0),
				(assign, ":troop", "$brothel_member_1"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(store_mul, ":player_state_state", ":troop_age_appearance", 200),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, ":troop", "$brothel_member_2"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(store_mul, ":player_state_state", ":troop_age_appearance", 200),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, ":troop", "$brothel_member_3"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(store_mul, ":player_state_state", ":troop_age_appearance", 200),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, ":troop", "$brothel_member_4"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(store_mul, ":player_state_state", ":troop_age_appearance", 200),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, ":troop", "$brothel_member_5"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(store_mul, ":player_state_state", ":troop_age_appearance", 200),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, ":troop", "$brothel_member_6"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(store_mul, ":player_state_state", ":troop_age_appearance", 200),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, ":troop", "$brothel_member_7"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(store_mul, ":player_state_state", ":troop_age_appearance", 200),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, "$brothel_prev_income", ":value_2"),
				(try_begin),
					(gt, ":value_2", 0),
					(assign, reg8, ":value_2"),
					(display_message, "str_brothel_revenue_sum", 0x00ff9000),
					(call_script, "script_party_money_level_diff", "p_main_party", ":value_2", 87),
				(try_end),
				(try_begin),
					(gt, ":value_4", 0),
					(call_script, "script_wm_honor_change_diff", "trp_player", ":value_4", 34),
				(try_end),
			(try_end),
			(assign, "$nakepit_prev_income", 0),
			(try_begin),
				(is_between, "$nakepit_target_party", "p_pyongyang", "p_place_end"),
				(store_mul, ":value_2", 100, 15),
				(assign, ":value_4", 0),
				(assign, ":troop", "$nakepit_member_1"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(try_begin),
						(le, ":troop_age_appearance", 1),
						(assign, ":player_state_state", 6),
					(else_try),
						(ge, ":troop_age_appearance", 4),
						(assign, ":player_state_state", 4),
					(else_try),
						(assign, ":player_state_state", 2),
					(try_end),
					(val_mul, ":player_state_state", 100),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, ":troop", "$nakepit_member_2"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(try_begin),
						(le, ":troop_age_appearance", 1),
						(assign, ":player_state_state", 6),
					(else_try),
						(ge, ":troop_age_appearance", 4),
						(assign, ":player_state_state", 4),
					(else_try),
						(assign, ":player_state_state", 2),
					(try_end),
					(val_mul, ":player_state_state", 100),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, ":troop", "$nakepit_member_3"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(try_begin),
						(le, ":troop_age_appearance", 1),
						(assign, ":player_state_state", 6),
					(else_try),
						(ge, ":troop_age_appearance", 4),
						(assign, ":player_state_state", 4),
					(else_try),
						(assign, ":player_state_state", 2),
					(try_end),
					(val_mul, ":player_state_state", 100),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, ":troop", "$nakepit_member_4"),
				(try_begin),
					(is_between, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
					(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
					(troop_get_slot, ":troop_age_appearance", ":troop", slot_troop_age_appearance),
					(try_begin),
						(le, ":troop_age_appearance", 1),
						(assign, ":player_state_state", 6),
					(else_try),
						(ge, ":troop_age_appearance", 4),
						(assign, ":player_state_state", 4),
					(else_try),
						(assign, ":player_state_state", 2),
					(try_end),
					(val_mul, ":player_state_state", 100),
					(val_add, ":value_2", ":player_state_state"),
					(val_add, ":value_4", 1),
				(try_end),
				(assign, "$nakepit_prev_income", ":value_2"),
				(try_begin),
					(gt, ":value_2", 0),
					(assign, reg8, ":value_2"),
					(display_message, "str_fightpit_revenue_sum", 0x00ff9000),
					(call_script, "script_party_money_level_diff", "p_main_party", ":value_2", 87),
				(try_end),
				(try_begin),
					(gt, ":value_4", 0),
					(call_script, "script_wm_honor_change_diff", "trp_player", ":value_4", 34),
				(try_end),
			(try_end),
			(try_begin),
				(is_between, "$hidout_target_party", "p_pyongyang", "p_place_end"),
				(assign, ":value_2", 0),
				(val_add, ":value_2", 1000),
				(val_add, ":value_2", 1000),
				(try_begin),
					(eq, "$hideout_build_prison", 1),
					(val_add, ":value_2", 500),
				(try_end),
				(try_begin),
					(eq, "$hideout_build_torture", 1),
					(val_add, ":value_2", 500),
				(try_end),
				(try_begin),
					(gt, ":value_2", 0),
					(assign, reg8, ":value_2"),
					(display_message, "str_hideout_mainte", 0x00ff9000),
					(call_script, "script_party_money_level_diff", "p_main_party", ":value_2", 34),
				(try_end),
			(try_end),
			(assign, ":value_2", 0),
			(try_for_range, ":troop", "trp_tt_lady_01_01", "trp_tt_lady_end"),
				(troop_slot_eq, ":troop", slot_troop_leaded_party, 3),
				(val_add, ":value_2", 1),
			(try_end),
			(try_begin),
				(gt, ":value_2", 0),
				(val_mul, ":value_2", 50),
				(assign, reg8, ":value_2"),
				(display_message, "str_slave_mainte", 0x00ff9000),
				(call_script, "script_party_money_level_diff", "p_main_party", ":value_2", 34),
			(try_end)
		]),

	(0.0, 0.0, 168.0,
		[],

		[
			(try_begin),
				(ge, "$weekk_count", 4),
				(assign, "$weekk_count", 1),
			(else_try),
				(val_add, "$weekk_count", 1),
			(try_end),
			(try_begin),
				(this_or_next|eq, "$weekk_count", 2),
				(eq, "$weekk_count", 4),
				(try_begin),
					(gt, "$main_q_step", 0),
					(lt, "$main_q_step", 19),
					(display_message, "str_mq_camp_menu_tip_ala", 0x00ffff00),
				(try_end),
				(store_attribute_level, ":attribute_level_player_2", "trp_player", 2),
				(try_begin),
					(gt, ":attribute_level_player_2", 40),
					(assign, ":attribute_level_player_2", 40),
				(try_end),
				(assign, reg8, ":attribute_level_player_2"),
				(val_mul, ":attribute_level_player_2", 5),
				(assign, reg9, ":attribute_level_player_2"),
				(display_message, "str_int_exp_rep"),
				(call_script, "script_int_exp_diff", ":attribute_level_player_2"),
			(try_end),
			(try_begin),
				(ge, "$weekk_count", 2),
				(try_for_range, ":party", "p_pyongyang", "p_place_end"),
					(store_faction_of_party, ":faction_of_party_party", ":party"),
					(eq, ":faction_of_party_party", "fac_neutral"),
					(party_set_flags, ":party", 256, 1),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$start_age", 1184),
				(try_for_range, ":party", "p_wasteland1", "p_ruin_1"),
					(party_set_flags, ":party", 256, 1),
				(try_end),
			(try_end),
			(call_script, "script_error_party_remove")
		]),

	(0.0, 0.0, 24.0,
		[],

		[
		#musicbox
		#(try_begin),
		#(assign, :situation, music_set_situation),
		#(neq, music_set_situation, mtf_sit_travel),
		#(music_set_situation, 0x00010000),
		
		#(try_end),
			(try_begin),
				(ge, "$dayy_count", 7),
				(assign, "$dayy_count", 1),
			(else_try),
				(val_add, "$dayy_count", 1),
			(try_end),
			(try_begin),
				(eq, "$dayy_two", 1),
				(assign, "$dayy_two", 0),
			(else_try),
				(assign, "$dayy_two", 1),
			(try_end),
			(try_begin),
				(ge, "$dayy_three", 3),
				(assign, "$dayy_three", 1),
			(else_try),
				(val_add, "$dayy_three", 1),
			(try_end),
			(try_begin),
				(ge, "$dayy_four", 4),
				(assign, "$dayy_four", 1),
			(else_try),
				(val_add, "$dayy_four", 1),
			(try_end),
			(try_begin),
				(gt, "$main_q_day", 0),
				(val_sub, "$main_q_day", 1),
				(try_begin),
					(eq, "$main_q_step", 3),
					(assign, reg8, "$main_q_day"),
					(display_message, "str_mq_1_3b"),
				(try_end),
			(try_end),
			(call_script, "script_wm_check_faction_castle_num_regular_activate"),
			(call_script, "script_check_faction_army_power_and_food"),
			(try_for_range, ":faction", "fac_kingdom_1", "fac_undeads"),
				(faction_slot_eq, ":faction", slot_faction_player_alarm, 1),
				(neq, ":faction", "fac_kingdoms_end"),
				(faction_get_slot, ":faction_25", ":faction", 25),
				(faction_get_slot, ":faction_number_of_parties", ":faction", slot_faction_number_of_parties),
				(faction_get_slot, ":faction_28", ":faction", 28),
				(try_begin),
					(is_between, ":faction_number_of_parties", "p_pyongyang", "p_place_end"),
					(store_faction_of_party, ":faction_of_party_faction_number_of_parties", ":faction_number_of_parties"),
					(neg|faction_slot_eq, ":faction_of_party_faction_number_of_parties", slot_faction_player_alarm, 1),
					(faction_set_slot, ":faction", slot_faction_number_of_parties, 1),
					(faction_set_slot, ":faction", 28, 0),
				(else_try),
					(le, ":faction_28", 0),
					(lt, ":faction_25", 25000),
					(faction_set_slot, ":faction", slot_faction_number_of_parties, 1),
					(faction_set_slot, ":faction", 28, 0),
				(else_try),
					(is_between, ":faction_number_of_parties", "p_pyongyang", "p_place_end"),
					(store_faction_of_party, ":faction_of_party_faction_number_of_parties", ":faction_number_of_parties"),
					(eq, ":faction_of_party_faction_number_of_parties", ":faction"),
					(faction_set_slot, ":faction", slot_faction_number_of_parties, 1),
					(faction_set_slot, ":faction", 28, 0),
				(else_try),
					(is_between, ":faction_number_of_parties", "p_pyongyang", "p_place_end"),
					(store_faction_of_party, ":faction_of_party_faction_number_of_parties", ":faction_number_of_parties"),
					(store_relation, ":relation_faction_of_party_faction_number_of_parties_faction", ":faction_of_party_faction_number_of_parties", ":faction"),
					(ge, ":relation_faction_of_party_faction_number_of_parties_faction", 0),
					(faction_set_slot, ":faction", slot_faction_number_of_parties, 1),
					(faction_set_slot, ":faction", 28, 0),
				(else_try),
					(neq, ":faction_number_of_parties", 1),
					(neg|is_between, ":faction_number_of_parties", "p_pyongyang", "p_place_end"),
					(faction_set_slot, ":faction", slot_faction_number_of_parties, 1),
					(faction_set_slot, ":faction", 28, 0),
				(try_end),
				(faction_get_slot, ":faction_number_of_parties", ":faction", slot_faction_number_of_parties),
				(ge, ":faction_25", 25000),
				(eq, ":faction_number_of_parties", 1),
				(call_script, "script_temp_save_number11_initialize"),
				(try_for_range, ":party", "p_pyongyang", "p_place_end"),
					(store_faction_of_party, ":faction_of_party_party", ":party"),
					(eq, ":faction_of_party_party", ":faction"),
					(try_for_range, ":number", 53, 63),
						(party_get_slot, ":party_number", ":party", ":number"),
						(store_faction_of_party, ":faction_of_party_faction_number_of_parties", ":party_number"),
						(faction_slot_eq, ":faction_of_party_faction_number_of_parties", slot_faction_player_alarm, 1),
						(store_relation, ":relation_faction_faction_of_party_faction_number_of_parties", ":faction", ":faction_of_party_faction_number_of_parties"),
						(lt, ":relation_faction_faction_of_party_faction_number_of_parties", 0),
						(call_script, "script_party_count_fit_for_battle", ":party_number"),
						(assign, ":var_12", reg0),
						(lt, ":var_12", 11000),
						(call_script, "script_temp_save_number11_inject", ":party_number"),
					(try_end),
				(try_end),
				(call_script, "script_temp_save_number11_choice_rand"),
				(try_begin),
					(is_between, "$wm_target_number11", "p_pyongyang", "p_place_end"),
					(store_faction_of_party, ":faction_of_party_faction_number_of_parties", "$wm_target_number11"),
					(faction_slot_eq, ":faction_of_party_faction_number_of_parties", slot_faction_player_alarm, 1),
					(store_relation, ":relation_faction_faction_of_party_faction_number_of_parties", ":faction", ":faction_of_party_faction_number_of_parties"),
					(lt, ":relation_faction_faction_of_party_faction_number_of_parties", 0),
					(faction_set_slot, ":faction", slot_faction_number_of_parties, "$wm_target_number11"),
					(try_begin),
						(ge, ":faction", "fac_kingdom_1"),
						(this_or_next|eq, ":faction", "$contract_fac"),
						(eq, ":faction", "$wm_player_fac"),
						(str_store_party_name, 1, "$wm_target_number11"),
						(display_message, "str_attack_targett", 0x00ff0000),
						(party_relocate_near_party, "p_attack_target", "$wm_target_number11", 0),
						(party_set_flags, "p_attack_target", 256, 0),
						(party_set_icon, "p_attack_target", "icon_attack_target"),
					(try_end),
				(else_try),
					(neg|is_between, "$wm_target_number11", "p_pyongyang", "p_place_end"),
					(call_script, "script_temp_save_number11_initialize"),
					(try_for_range, ":party", "p_pyongyang", "p_place_end"),
						(store_faction_of_party, ":faction_of_party_party", ":party"),
						(eq, ":faction_of_party_party", ":faction"),
						(try_for_range, ":number", 53, 63),
							(party_get_slot, ":party_number", ":party", ":number"),
							(store_faction_of_party, ":faction_of_party_faction_number_of_parties", ":party_number"),
							(faction_slot_eq, ":faction_of_party_faction_number_of_parties", slot_faction_player_alarm, 1),
							(store_relation, ":relation_faction_faction_of_party_faction_number_of_parties", ":faction", ":faction_of_party_faction_number_of_parties"),
							(lt, ":relation_faction_faction_of_party_faction_number_of_parties", 0),
							(call_script, "script_temp_save_number11_inject", ":party_number"),
						(try_end),
					(try_end),
					(call_script, "script_temp_save_number11_choice_rand"),
					(try_begin),
						(is_between, "$wm_target_number11", "p_pyongyang", "p_place_end"),
						(store_faction_of_party, ":faction_of_party_faction_number_of_parties", "$wm_target_number11"),
						(faction_slot_eq, ":faction_of_party_faction_number_of_parties", slot_faction_player_alarm, 1),
						(store_relation, ":relation_faction_faction_of_party_faction_number_of_parties", ":faction", ":faction_of_party_faction_number_of_parties"),
						(lt, ":relation_faction_faction_of_party_faction_number_of_parties", 0),
						(faction_set_slot, ":faction", slot_faction_number_of_parties, "$wm_target_number11"),
						(try_begin),
							(ge, ":faction", "fac_kingdom_1"),
							(this_or_next|eq, ":faction", "$contract_fac"),
							(eq, ":faction", "$wm_player_fac"),
							(str_store_party_name, 1, "$wm_target_number11"),
							(display_message, "str_attack_targett", 0x00ff0000),
							(party_relocate_near_party, "p_attack_target", "$wm_target_number11", 0),
							(party_set_flags, "p_attack_target", 256, 0),
							(party_set_icon, "p_attack_target", "icon_attack_target"),
						(try_end),
					(try_end),
				(try_end),
				(try_begin),
					(ge, ":faction", "fac_kingdom_1"),
					(this_or_next|eq, ":faction", "$contract_fac"),
					(eq, ":faction", "$wm_player_fac"),
					(faction_get_slot, ":faction_number_of_parties_2", ":faction", slot_faction_number_of_parties),
					(neg|is_between, ":faction_number_of_parties_2", "p_pyongyang", "p_place_end"),
					(party_set_flags, "p_attack_target", 256, 1),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 6),
				(call_script, "script_wm_turn_dev_output_div_build_ai"),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 1),
				(call_script, "script_faction_public_opinion_sett"),
				(call_script, "script_check_faction_border_faction"),
				(call_script, "script_no_border_faction_enemy_peace"),
				(try_begin),
					(eq, "$weekk_count", 1),
					(call_script, "script_rand_between_faction_diplomacy", "fac_kingdom_1", "fac_kingdom_16"),
					(call_script, "script_wm_trade_price_try_for"),
				(else_try),
					(eq, "$weekk_count", 2),
					(call_script, "script_rand_between_faction_diplomacy", "fac_kingdom_17", "fac_kingdom_32"),
					(call_script, "script_wm_place_owner_sett_scan", 1),
				(else_try),
					(eq, "$weekk_count", 3),
					(call_script, "script_rand_between_faction_diplomacy", "fac_kingdom_33", "fac_kingdom_48"),
					(call_script, "script_wm_trade_price_try_for"),
				(else_try),
					(eq, "$weekk_count", 4),
					(call_script, "script_rand_between_faction_diplomacy", "fac_kingdom_49", "fac_japan_people"),
					(call_script, "script_wm_place_owner_sett_scan", 1),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 2),
				(try_begin),
					(gt, "$ai_holywar_delay", 0),
					(val_sub, "$ai_holywar_delay", 1),
				(try_end),
				(try_begin),
					(le, "$ai_holywar_delay", 0),
					(store_random_in_range, ":random_in_range_0_10", 0, 10),
					(try_begin),
						(eq, ":random_in_range_0_10", 0),
						(call_script, "script_ai_rand_holywar"),
					(else_try),
						(eq, ":random_in_range_0_10", 1),
						(this_or_next|eq, "$start_age", 0),
						(eq, "$start_age", 1184),
						(store_faction_of_party, ":faction_of_party_party", "p_jerusalem"),
						(faction_get_slot, ":faction_of_party_party_27", ":faction_of_party_party", 27),
						(try_begin),
							(neq, ":faction_of_party_party_27", 1),
							(call_script, "script_holywar_reln_set", 1, ":faction_of_party_party_27", "p_jerusalem"),
						(else_try),
							(neq, ":faction_of_party_party_27", 3),
							(call_script, "script_holywar_reln_set", 3, ":faction_of_party_party_27", "p_jerusalem"),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 3),
				(store_random_in_range, ":random_in_range_0_2", 0, 2),
				(try_begin),
					(eq, ":random_in_range_0_2", 0),
					(try_begin),
						(eq, "$weekk_count", 1),
						(call_script, "script_disaster_rand_execute", 9),
					(else_try),
						(eq, "$weekk_count", 2),
						(call_script, "script_disaster_rand_execute", 7),
						(call_script, "script_npc_courtship_event"),
					(else_try),
						(eq, "$weekk_count", 3),
						(call_script, "script_disaster_rand_execute", 6),
					(else_try),
						(eq, "$weekk_count", 4),
						(call_script, "script_disaster_rand_execute", 5),
						(call_script, "script_npc_courtship_event"),
					(try_end),
				(try_end),
				(store_random_in_range, "$temp_glob_rand_1", 1081, 1252),
				(store_random_in_range, "$temp_glob_rand_2", 1081, 1252),
				(store_random_in_range, "$temp_glob_rand_3", 1081, 1252),
				(store_random_in_range, "$temp_glob_rand_4", 1081, 1252),
				(store_random_in_range, "$temp_glob_rand_5", 1081, 1252),
				(store_random_in_range, "$temp_glob_rand_6", 1081, 1252),
				(store_random_in_range, "$temp_glob_rand_7", 1081, 1252),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 5),
				(try_for_range, ":faction_2", "fac_kingdom_1", "fac_undeads"),
					(faction_slot_eq, ":faction_2", slot_faction_player_alarm, 1),
					(try_for_range, ":number", 56, 76),
						(faction_get_slot, ":faction_2_number", ":faction_2", ":number"),
						(gt, ":faction_2_number", 0),
						(neg|is_between, ":faction_2_number", "p_temp_party", "p_reserved_5"),
						(neq, ":faction_2_number", "p_reserved_5"),
						(party_is_active, ":faction_2_number"),
						(party_slot_eq, ":faction_2_number", slot_party_type, 1),
						(party_stack_get_troop_id, ":party_stack_troop_id_faction_2_number_0", ":faction_2_number", 0),
						(this_or_next|is_between, ":party_stack_troop_id_faction_2_number_0", "trp_tt_lord_01_00", "trp_tt_lord_end"),
						(is_between, ":party_stack_troop_id_faction_2_number_0", "trp_temp_commander_fac_01", "trp_temp_commander_end"),
						(assign, ":value", 100),
						(store_div, ":value_2", ":value", 5),
						(call_script, "script_ai_equip_supp_depend_fac", ":faction_2_number", ":value_2", ":faction_2"),
					(try_end),
				(try_end),
				(try_begin),
					(assign, ":var_22", "p_main_party"),
					(try_begin),
						(neq, "$supp_equip_01", 1),
						(party_set_slot, ":var_22", slot_party_commander_party, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_02", 1),
						(party_set_slot, ":var_22", slot_party_following_player, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_03", 1),
						(party_set_slot, ":var_22", slot_party_follow_player_until_time, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_04", 1),
						(party_set_slot, ":var_22", slot_party_dont_follow_player_until_time, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_05", 1),
						(party_set_slot, ":var_22", slot_village_raided_by, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_06", 1),
						(party_set_slot, ":var_22", slot_village_state, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_07", 1),
						(party_set_slot, ":var_22", slot_village_raid_progress, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_08", 1),
						(party_set_slot, ":var_22", slot_village_recover_progress, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_09", 1),
						(party_set_slot, ":var_22", slot_village_smoke_added, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_10", 1),
						(party_set_slot, ":var_22", slot_village_infested_by_bandits, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_11", 1),
						(party_set_slot, ":var_22", 40, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_12", 1),
						(party_set_slot, ":var_22", slot_center_last_visited_by_lord, 0),
					(try_end),
					(try_begin),
						(neq, "$supp_equip_13", 1),
						(party_set_slot, ":var_22", slot_center_last_player_alarm_hour, 0),
					(try_end),
					(assign, ":var_23", 0),
					(try_begin),
						(eq, "$supp_equip_01", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_02", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_03", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_04", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_05", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_06", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_07", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_08", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_09", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_10", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_11", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_12", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_13", 1),
						(val_add, ":var_23", 1),
					(try_end),
					(gt, ":var_23", 0),
					(assign, ":value", 100),
					(assign, ":var_24", 5000),
					(store_div, ":value_2", ":value", ":var_23"),
					(store_div, ":value_3", ":var_24", ":var_23"),
					(try_begin),
						(eq, "$supp_equip_01", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 30, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_02", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 31, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_03", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 32, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_04", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 33, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_05", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 34, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_06", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 35, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_07", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 36, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_08", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 37, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_09", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 38, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_10", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 39, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_11", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 40, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_12", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 41, ":value_2", ":value_3"),
					(try_end),
					(try_begin),
						(eq, "$supp_equip_13", 1),
						(call_script, "script_equip_supp_to_party", ":var_22", 42, ":value_2", ":value_3"),
					(try_end),
				(try_end),
				(try_begin),
					(eq, "$r_player_class", 5),
					(party_set_slot, "p_main_party", slot_center_last_visited_by_lord, 1000),
				(else_try),
					(eq, "$r_player_class", 3),
					(party_set_slot, "p_main_party", slot_village_smoke_added, 1000),
				(try_end),
				(try_begin),
					(gt, "$workshop_target_party", 0),
					(gt, "$workshop_slave", 50),
					(is_between, "$wm_player_fac", "fac_kingdom_1", "fac_kingdoms_end"),
					(faction_slot_eq, "$wm_player_fac", slot_faction_ai_rationale, 0),
					(display_message, "str_slave_not_fac", 0x00ff9000),
					(call_script, "script_wm_honor_change_diff", "trp_player", 2, 34),
				(try_end),
				(try_for_range, ":faction", "fac_kingdom_1", "fac_undeads"),
					(faction_get_slot, ":faction_28", ":faction", 28),
					(gt, ":faction_28", 0),
					(val_sub, ":faction_28", 1),
					(faction_set_slot, ":faction", 28, ":faction_28"),
				(try_end),
			(try_end),
			(try_begin),
				(gt, "$qquest_type", 0),
				(le, "$qquest_time_day", 0),
				(call_script, "script_qquest_initialize"),
				(display_message, "str_questfail_time", 0x00ffff00),
			(else_try),
				(gt, "$qquest_time_day", 0),
				(neq, "$qquest_progress", 1),
				(val_sub, "$qquest_time_day", 1),
			(try_end),
			(try_begin),
				(neq, "$qquest_type", 23),
				(neq, "$qquest_type", 24),
				(party_set_flags, "p_for_quest_villa", 256, 1),
				(party_set_flags, "p_for_quest_villa", 16384, 0),
			(try_end),
			(try_begin),
				(is_between, "$workshop_target_party", "p_pyongyang", "p_place_end"),
				(store_faction_of_party, ":faction_of_party_party", "$workshop_target_party"),
				(store_relation, ":relation_faction_of_party_faction_number_of_parties_faction", ":faction_of_party_party", "$wm_player_fac"),
				(party_get_slot, ":workshop_target_party_town_castle", "$workshop_target_party", slot_town_castle),
				(try_begin),
					(lt, ":relation_faction_of_party_faction_number_of_parties_faction", 0),
					(str_store_party_name, 7, "p_workshop_party"),
					(assign, "$workshop_target_party", 0),
					(assign, "$workshop_slave", 0),
					(party_set_flags, "p_workshop_party", 256, 1),
					(display_message, "str_workshop_enemy"),
					(play_sound, "snd_sabotagee"),
				(else_try),
					(neq, ":workshop_target_party_town_castle", "$workshop_target_res_slot"),
					(str_store_party_name, 7, "p_workshop_party"),
					(str_store_item_name, 8, "$workshop_target_product"),
					(assign, "$workshop_target_party", 0),
					(assign, "$workshop_slave", 0),
					(party_set_flags, "p_workshop_party", 256, 1),
					(display_message, "str_workshop_depleted"),
				(else_try),
					(gt, "$workshop_slave", 50),
					(store_random_in_range, ":random_in_range_0_4", 0, 4),
					(store_mul, ":value_4", 25, 5),
					(try_begin),
						(eq, "$workshop_work_level", ":value_4"),
						(ge, ":random_in_range_0_4", 1),
						(val_sub, "$workshop_slave", 1),
					(else_try),
						(eq, "$workshop_work_level", 100),
						(ge, ":random_in_range_0_4", 2),
						(val_sub, "$workshop_slave", 1),
					(else_try),
						(eq, "$workshop_work_level", 75),
						(ge, ":random_in_range_0_4", 3),
						(val_sub, "$workshop_slave", 1),
					(try_end),
					(store_mul, ":value_5", "$workshop_slave", "$workshop_work_level"),
					(val_div, ":value_5", 100),
					(val_add, "$workshop_product_cur", ":value_5"),
					(try_begin),
						(gt, "$workshop_product_cur", "$workshop_target_price"),
						(val_sub, "$workshop_product_cur", "$workshop_target_price"),
						(val_add, "$workshop_product_stock", 1),
						(try_begin),
							(gt, "$workshop_product_stock", 10),
							(assign, "$workshop_product_stock", 10),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(neg|is_between, "$contract_fac", "fac_kingdom_1", "fac_kingdoms_end"),
				(gt, "$contract_time", 0),
				(assign, "$contract_time", 0),
			(try_end),
			(try_begin),
				(le, "$contract_time", 0),
				(assign, "$contract_fac", 0),
			(try_end),
			(try_begin),
				(gt, "$contract_time", 0),
				(val_sub, "$contract_time", 1),
				(is_between, "$contract_fac", "fac_kingdom_1", "fac_kingdoms_end"),
				(assign, ":var_30", "$contract_fac"),
				(try_for_range, ":faction", "fac_kingdom_1", "fac_undeads"),
					(neq, ":faction", ":var_30"),
					(faction_slot_eq, ":faction", slot_faction_player_alarm, 1),
					(call_script, "script_wm_copy_faction_relation", ":var_30", ":faction", ":var_30"),
				(try_end),
				(call_script, "script_troop_contribution_diff", "trp_player", 1, 34),
			(try_end),
			(try_begin),
				(is_between, "$contract_fac", "fac_kingdom_1", "fac_kingdoms_end"),
				(set_show_messages, 0),
				(troop_get_slot, ":player_does_not_give_quest", "trp_player", slot_troop_does_not_give_quest),
				(val_div, ":player_does_not_give_quest", 23),
				(set_show_messages, 1),
				(try_begin),
					(le, ":player_does_not_give_quest", 0),
					(call_script, "script_wm_mercenary_dispose"),
					(display_message, "str_merc_too_lazy", 0x00ff9000),
				(else_try),
					(le, "$contract_time", 0),
					(call_script, "script_wm_mercenary_dispose"),
				(try_end),
			(try_end),
			(try_begin),
				(is_between, "$wm_player_fac", "fac_kingdom_1", "fac_kingdoms_end"),
				(try_for_range, ":faction", "fac_kingdom_1", "fac_undeads"),
					(neq, ":faction", "$wm_player_fac"),
					(neq, ":faction", "fac_kingdoms_end"),
					(store_relation, ":relation_faction_of_party_faction_number_of_parties_faction", "$wm_player_fac", ":faction"),
					(call_script, "script_set_player_relation_with_faction_no_mess", ":faction", ":relation_faction_of_party_faction_number_of_parties_faction"),
				(try_end),
			(try_end),
			(try_begin),
				(is_between, "$nakepit_target_party", "p_pyongyang", "p_place_end"),
				(store_faction_of_party, ":faction_of_party_party", "$nakepit_target_party"),
				(store_relation, ":relation_faction_of_party_faction_number_of_parties_faction", ":faction_of_party_party", "$wm_player_fac"),
				(lt, ":relation_faction_of_party_faction_number_of_parties_faction", 0),
				(str_store_party_name, 7, "p_nakepit_party"),
				(assign, "$nakepit_target_party", 0),
				(party_set_flags, "p_nakepit_party", 256, 1),
				(display_message, "str_workshop_enemy"),
				(play_sound, "snd_sabotagee"),
			(try_end),
			(try_begin),
				(is_between, "$brothel_target_party", "p_pyongyang", "p_place_end"),
				(store_faction_of_party, ":faction_of_party_party", "$brothel_target_party"),
				(store_relation, ":relation_faction_of_party_faction_number_of_parties_faction", ":faction_of_party_party", "$wm_player_fac"),
				(lt, ":relation_faction_of_party_faction_number_of_parties_faction", 0),
				(str_store_party_name, 7, "p_brothel_party"),
				(assign, "$brothel_target_party", 0),
				(party_set_flags, "p_brothel_party", 256, 1),
				(display_message, "str_workshop_enemy"),
				(play_sound, "snd_sabotagee"),
			(try_end),
			(try_begin),
				(is_between, "$hidout_target_party", "p_pyongyang", "p_place_end"),
				(store_faction_of_party, ":faction_of_party_party", "$brothel_target_party"),
				(store_relation, ":relation_faction_of_party_faction_number_of_parties_faction", ":faction_of_party_party", "$wm_player_fac"),
				(lt, ":relation_faction_of_party_faction_number_of_parties_faction", 0),
				(str_store_party_name, 7, "p_ply_hideout"),
				(assign, "$hidout_target_party", 0),
				(assign, "$hideout_build_prison", 0),
				(assign, "$hideout_build_torture", 0),
				(party_set_flags, "p_ply_hideout", 256, 1),
				(display_message, "str_workshop_enemy"),
				(play_sound, "snd_sabotagee"),
			(try_end),
			(call_script, "script_player_faction_relation_rescan"),
			(try_begin),
				(eq, "$dayy_two", 1),
				(store_random_in_range, "$glob_weather", 0, 3),
				(try_begin),
					(eq, "$glob_weather", 2),
					(store_random_in_range, ":random_in_range_0_4", 0, 2),
					(eq, ":random_in_range_0_4", 0),
					(assign, "$glob_weather", 0),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$dayy_two", 1),
				(troop_slot_ge, "trp_player", 16, 1),
				(troop_get_slot, ":player_player_order_state", "trp_player", slot_troop_player_order_state),
				(store_add, ":value_6", "str_wound_0", ":player_player_order_state"),
				(str_store_string, 8, ":value_6"),
				(display_message, "str_health_status_s8"),
			(try_end),
			(try_begin),
				(eq, "$dayy_three", 1),
				(call_script, "script_bandit_party_spawn"),
			(try_end),
			(try_begin),
				(eq, "$dayy_four", 1),
				(call_script, "script_wm_wound_disease_event"),
			(try_end),
			(call_script, "script_lord_lady_mainland_sett"),
			(try_begin),
				(eq, "$dayy_four", 1),
				(store_attribute_level, ":attribute_level_player_3", "trp_player", 3),
				(try_begin),
					(gt, ":attribute_level_player_3", 40),
					(assign, ":attribute_level_player_3", 40),
				(try_end),
				(assign, reg8, ":attribute_level_player_3"),
				(val_mul, ":attribute_level_player_3", 2),
				(assign, reg9, ":attribute_level_player_3"),
				(display_message, "str_charisma_train"),
				(call_script, "script_exp_reward_for_common_troop", ":attribute_level_player_3"),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 2),
				(gt, "$orphan_girl_troop_id", 0),
				(lt, "$orphan_grown_count", 240),
				(try_begin),
					(ge, "$orphan_train_type", 23),
					(store_skill_level, ":skill_level_orphan_train_type_orphan_girl_troop_id", "$orphan_train_type", "$orphan_girl_troop_id"),
					(lt, ":skill_level_orphan_train_type_orphan_girl_troop_id", 9),
					(troop_raise_skill, "$orphan_girl_troop_id", "$orphan_train_type", 1),
				(else_try),
					(eq, "$orphan_train_type", 1),
					(store_attribute_level, ":attribute_level_orphan_girl_troop_id_0", "$orphan_girl_troop_id", 0),
					(lt, ":attribute_level_orphan_girl_troop_id_0", 60),
					(troop_raise_attribute, "$orphan_girl_troop_id", 0, 1),
					(troop_raise_proficiency, "$orphan_girl_troop_id", 0, 10),
					(troop_raise_proficiency, "$orphan_girl_troop_id", 1, 10),
					(troop_raise_proficiency, "$orphan_girl_troop_id", 2, 10),
				(else_try),
					(eq, "$orphan_train_type", 2),
					(store_attribute_level, ":attribute_level_orphan_girl_troop_id_0", "$orphan_girl_troop_id", 1),
					(lt, ":attribute_level_orphan_girl_troop_id_0", 60),
					(troop_raise_attribute, "$orphan_girl_troop_id", 1, 1),
					(troop_raise_proficiency, "$orphan_girl_troop_id", 3, 10),
					(troop_raise_proficiency, "$orphan_girl_troop_id", 4, 10),
					(troop_raise_proficiency, "$orphan_girl_troop_id", 5, 10),
					(troop_raise_proficiency, "$orphan_girl_troop_id", 6, 10),
				(else_try),
					(eq, "$orphan_train_type", 3),
					(store_attribute_level, ":attribute_level_orphan_girl_troop_id_0", "$orphan_girl_troop_id", 3),
					(lt, ":attribute_level_orphan_girl_troop_id_0", 60),
					(troop_raise_attribute, "$orphan_girl_troop_id", 3, 1),
				(try_end),
				(store_attribute_level, ":attribute_level_orphan_girl_troop_id_0", "$orphan_girl_troop_id", 3),
				(try_begin),
					(ge, ":attribute_level_orphan_girl_troop_id_0", 45),
					(assign, "$orphan_girl_troop_id", "trp_tt_lady_orphan_05"),
					(call_script, "script_orphan_skill_copy"),
				(else_try),
					(ge, ":attribute_level_orphan_girl_troop_id_0", 35),
					(assign, "$orphan_girl_troop_id", "trp_tt_lady_orphan_04"),
					(call_script, "script_orphan_skill_copy"),
				(else_try),
					(ge, ":attribute_level_orphan_girl_troop_id_0", 25),
					(assign, "$orphan_girl_troop_id", "trp_tt_lady_orphan_03"),
					(call_script, "script_orphan_skill_copy"),
				(else_try),
					(ge, ":attribute_level_orphan_girl_troop_id_0", 15),
					(assign, "$orphan_girl_troop_id", "trp_tt_lady_orphan_02"),
					(call_script, "script_orphan_skill_copy"),
				(try_end),
				(val_add, "$orphan_grown_count", 1),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 3),
				(call_script, "script_slave_progress_try"),
				(call_script, "script_qquest_lord_lady_sett"),
				(try_begin),
					(this_or_next|eq, "$trade_contract_a", 1),
					(eq, "$trade_contract_b", 1),
					(call_script, "script_respawn_player_traders_party"),
				(try_end),
				(call_script, "script_wm_party_quest_slot_sett"),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 2),
				(val_add, "$player_bath_cooltime", 1),
				(try_begin),
					(gt, "$player_bath_cooltime", 11),
					(display_message, "str_player_bath_alarm", 0x00ff0000),
					(call_script, "script_wm_troop_wound_disease_slot", "trp_player", 5),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 1),
				(call_script, "script_quest_party_spawn"),
				(call_script, "script_quest_party_time_sett"),
				(call_script, "script_quest_party_remove"),
			(try_end),
			(assign, ":var_37", 0),
			(assign, ":var_38", 0),
			(assign, ":var_39", 0),
			(assign, ":var_40", 0),
			(assign, ":var_41", 0),
			(assign, ":var_42", 0),
			(party_get_num_companion_stacks, ":num_companion_stacks_main_party", "p_main_party"),
			(try_for_range, ":localvariable", 0, ":num_companion_stacks_main_party"),
				(party_stack_get_troop_id, ":party_stack_troop_id_main_party_localvariable", "p_main_party", ":localvariable"),
				(gt, ":party_stack_troop_id_main_party_localvariable", "trp_army_size_troop"),
				(neg|troop_is_hero, ":party_stack_troop_id_main_party_localvariable"),
				(party_stack_get_size, ":party_stack_size_main_party_localvariable", "p_main_party", ":localvariable"),
				(try_begin),
					(gt, ":party_stack_size_main_party_localvariable", 0),
					(store_character_level, ":character_level_party_stack_troop_id_main_party_localvariable", ":party_stack_troop_id_main_party_localvariable"),
					(try_begin),
						(lt, ":character_level_party_stack_troop_id_main_party_localvariable", 18),
						(val_add, ":var_37", ":party_stack_size_main_party_localvariable"),
					(else_try),
						(lt, ":character_level_party_stack_troop_id_main_party_localvariable", 21),
						(val_add, ":var_38", ":party_stack_size_main_party_localvariable"),
					(else_try),
						(lt, ":character_level_party_stack_troop_id_main_party_localvariable", 25),
						(val_add, ":var_39", ":party_stack_size_main_party_localvariable"),
					(else_try),
						(lt, ":character_level_party_stack_troop_id_main_party_localvariable", 28),
						(val_add, ":var_40", ":party_stack_size_main_party_localvariable"),
					(else_try),
						(lt, ":character_level_party_stack_troop_id_main_party_localvariable", 30),
						(val_add, ":var_41", ":party_stack_size_main_party_localvariable"),
					(else_try),
						(val_add, ":var_42", ":party_stack_size_main_party_localvariable"),
					(try_end),
				(try_end),
			(try_end),
			(store_add, ":value_7", ":var_41", ":var_42"),
			(store_add, ":value_8", ":value_7", ":var_40"),
			(try_begin),
				(gt, ":var_42", 20),
				(store_sub, ":value_9", ":var_42", 20),
				(call_script, "script_troop_recount_sett", ":value_9", 1, 30, 1000),
			(else_try),
				(gt, ":value_7", 40),
				(store_sub, ":value_9", ":value_7", 40),
				(call_script, "script_troop_recount_sett", ":value_9", 1, 28, 30),
			(else_try),
				(gt, ":value_8", 60),
			(try_end),
			(call_script, "script_lord_slot_troop_leader_state_fix"),
			(try_begin),
				(eq, "$dayy_count", 1),
				(party_set_flags, "p_tournament_flag_1", 256, 1),
				(party_set_flags, "p_tournament_flag_2", 256, 1),
				(party_set_flags, "p_tournament_flag_3", 256, 1),
				(party_set_flags, "p_tournament_flag_4", 256, 1),
				(party_set_flags, "p_tournament_flag_5", 256, 1),
				(party_set_flags, "p_tournament_flag_6", 256, 1),
				(party_set_flags, "p_tournament_flag_7", 256, 1),
				(party_set_flags, "p_tournament_flag_8", 256, 1),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 2),
				(store_random_in_range, "$tournament_place_1", "p_pyongyang", "p_place_end"),
				(party_set_slot, "$tournament_place_1", slot_party_last_toll_paid_hours, 1),
				(party_relocate_near_party, "p_tournament_flag_1", "$tournament_place_1", 0),
				(party_set_flags, "p_tournament_flag_1", 256, 0),
				(party_set_icon, "p_tournament_flag_1", "icon_tournament_flag"),
				(store_random_in_range, "$tournament_place_2", "p_pyongyang", "p_place_end"),
				(party_set_slot, "$tournament_place_2", slot_party_last_toll_paid_hours, 1),
				(party_relocate_near_party, "p_tournament_flag_2", "$tournament_place_2", 0),
				(party_set_flags, "p_tournament_flag_2", 256, 0),
				(party_set_icon, "p_tournament_flag_2", "icon_tournament_flag"),
				(store_random_in_range, "$tournament_place_3", "p_pyongyang", "p_place_end"),
				(party_set_slot, "$tournament_place_3", slot_party_last_toll_paid_hours, 1),
				(party_relocate_near_party, "p_tournament_flag_3", "$tournament_place_3", 0),
				(party_set_flags, "p_tournament_flag_3", 256, 0),
				(party_set_icon, "p_tournament_flag_3", "icon_tournament_flag"),
				(store_random_in_range, "$tournament_place_4", "p_pyongyang", "p_place_end"),
				(party_set_slot, "$tournament_place_4", slot_party_last_toll_paid_hours, 1),
				(party_relocate_near_party, "p_tournament_flag_4", "$tournament_place_4", 0),
				(party_set_flags, "p_tournament_flag_4", 256, 0),
				(party_set_icon, "p_tournament_flag_4", "icon_tournament_flag"),
				(store_random_in_range, "$tournament_place_5", "p_pyongyang", "p_place_end"),
				(party_set_slot, "$tournament_place_5", slot_party_last_toll_paid_hours, 1),
				(party_relocate_near_party, "p_tournament_flag_5", "$tournament_place_5", 0),
				(party_set_flags, "p_tournament_flag_5", 256, 0),
				(party_set_icon, "p_tournament_flag_5", "icon_tournament_flag"),
				(store_random_in_range, "$tournament_place_6", "p_pyongyang", "p_place_end"),
				(party_set_slot, "$tournament_place_6", slot_party_last_toll_paid_hours, 1),
				(party_relocate_near_party, "p_tournament_flag_6", "$tournament_place_6", 0),
				(party_set_flags, "p_tournament_flag_6", 256, 0),
				(party_set_icon, "p_tournament_flag_6", "icon_tournament_flag"),
				(store_random_in_range, "$tournament_place_7", "p_pyongyang", "p_place_end"),
				(party_set_slot, "$tournament_place_7", slot_party_last_toll_paid_hours, 1),
				(party_relocate_near_party, "p_tournament_flag_7", "$tournament_place_7", 0),
				(party_set_flags, "p_tournament_flag_7", 256, 0),
				(party_set_icon, "p_tournament_flag_7", "icon_tournament_flag"),
				(store_random_in_range, "$tournament_place_8", "p_pyongyang", "p_place_end"),
				(party_set_slot, "$tournament_place_8", slot_party_last_toll_paid_hours, 1),
				(party_relocate_near_party, "p_tournament_flag_8", "$tournament_place_8", 0),
				(party_set_flags, "p_tournament_flag_8", 256, 0),
				(party_set_icon, "p_tournament_flag_8", "icon_tournament_flag"),
			(try_end),
			(store_random_in_range, ":random_in_range_0_2", 0, 2),
			(try_begin),
				(eq, ":random_in_range_0_2", 0),
				(try_begin),
					(eq, "$dayy_count", 1),
					(call_script, "script_disaster_rand_execute", 11),
				(else_try),
					(eq, "$dayy_count", 2),
					(call_script, "script_disaster_rand_execute", 1),
				(else_try),
					(eq, "$dayy_count", 3),
					(call_script, "script_disaster_rand_execute", 2),
				(else_try),
					(eq, "$dayy_count", 4),
					(call_script, "script_disaster_rand_execute", 3),
				(else_try),
					(eq, "$dayy_count", 5),
					(call_script, "script_disaster_rand_execute", 4),
				(else_try),
					(eq, "$dayy_count", 6),
					(call_script, "script_disaster_rand_execute", 8),
				(else_try),
					(eq, "$dayy_count", 7),
					(call_script, "script_disaster_rand_execute", 10),
				(try_end),
			(try_end),
			(call_script, "script_caravan_party_spawn"),
			(try_begin),
				(eq, "$dayy_count", 4),
				(call_script, "script_wm_comp_separate", "$wm_comp_id_standby"),
				(call_script, "script_resilience_progress"),
			(try_end),
			(try_begin),
				(eq, "$g_sex_officer", "trp_player"),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party", "p_main_party"),
				(gt, ":party_size_wo_prisoners_main_party", 1),
				(val_sub, ":party_size_wo_prisoners_main_party", 1),
				(try_begin),
					(gt, ":party_size_wo_prisoners_main_party", 20),
					(store_random_in_range, ":party_size_wo_prisoners_main_party", 10, 21),
				(try_end),
				(val_add, "$Sex_num", ":party_size_wo_prisoners_main_party"),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 5),
				(assign, ":var_52", 0),
				(assign, ":var_53", 0),
				(try_begin),
					(gt, "$wm_comp_id_1", 0),
					(store_character_level, ":character_level_party_stack_troop_id_main_party_localvariable", "$wm_comp_id_1"),
					(val_add, ":var_53", ":character_level_party_stack_troop_id_main_party_localvariable"),
				(try_end),
				(try_begin),
					(gt, "$wm_comp_id_2", 0),
					(store_character_level, ":character_level_party_stack_troop_id_main_party_localvariable", "$wm_comp_id_2"),
					(val_add, ":var_53", ":character_level_party_stack_troop_id_main_party_localvariable"),
				(try_end),
				(try_begin),
					(gt, "$wm_comp_id_3", 0),
					(store_character_level, ":character_level_party_stack_troop_id_main_party_localvariable", "$wm_comp_id_3"),
					(val_add, ":var_53", ":character_level_party_stack_troop_id_main_party_localvariable"),
				(try_end),
				(try_begin),
					(gt, "$wm_comp_id_4", 0),
					(store_character_level, ":character_level_party_stack_troop_id_main_party_localvariable", "$wm_comp_id_4"),
					(val_add, ":var_53", ":character_level_party_stack_troop_id_main_party_localvariable"),
				(try_end),
				(try_begin),
					(gt, "$wm_comp_id_5", 0),
					(store_character_level, ":character_level_party_stack_troop_id_main_party_localvariable", "$wm_comp_id_5"),
					(val_add, ":var_53", ":character_level_party_stack_troop_id_main_party_localvariable"),
				(try_end),
				(val_mul, ":var_53", 10),
				(val_add, ":var_52", ":var_53"),
				(assign, ":var_54", 0),
				(try_for_range, ":troop", "trp_elite_troops_01", "trp_elite_troops_end"),
					(troop_slot_eq, ":troop", slot_troop_love_interest_1, 1),
					(store_character_level, ":character_level_party_stack_troop_id_main_party_localvariable", ":troop"),
					(val_mul, ":character_level_party_stack_troop_id_main_party_localvariable", 7),
					(val_add, ":var_54", ":character_level_party_stack_troop_id_main_party_localvariable"),
				(try_end),
				(val_add, ":var_52", ":var_54"),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party_2", "p_main_party"),
				(val_sub, ":party_size_wo_prisoners_main_party_2", 1),
				(try_begin),
					(is_between, "$contract_fac", "fac_kingdom_1", "fac_kingdoms_end"),
					(eq, "$r_player_class", 0),
					(assign, ":party_size_wo_prisoners_main_party_2", 0),
				(else_try),
					(is_between, "$contract_fac", "fac_kingdom_1", "fac_kingdoms_end"),
					(ge, ":party_size_wo_prisoners_main_party_2", 500),
					(val_div, ":party_size_wo_prisoners_main_party_2", 4),
				(else_try),
					(lt, ":party_size_wo_prisoners_main_party_2", 500),
					(assign, ":party_size_wo_prisoners_main_party_2", 0),
				(else_try),
					(gt, ":party_size_wo_prisoners_main_party_2", 3),
					(val_div, ":party_size_wo_prisoners_main_party_2", 3),
				(try_end),
				(val_add, ":var_52", ":party_size_wo_prisoners_main_party_2"),
				(assign, ":value_10", 0),
				(try_begin),
					(is_between, "$ply_staying_party_no", "p_pyongyang", "p_place_end"),
					(gt, "$ply_staying_army_size", 3),
					(store_div, ":value_10", "$ply_staying_army_size", 3),
				(try_end),
				(val_add, ":var_52", ":value_10"),
				(assign, ":value_11", 0),
				(party_get_num_companion_stacks, ":num_companion_stacks_main_party", "p_main_party"),
				(try_for_range, ":localvariable", 0, ":num_companion_stacks_main_party"),
					(party_stack_get_troop_id, ":party_stack_troop_id_main_party_localvariable", "p_main_party", ":localvariable"),
					(gt, ":party_stack_troop_id_main_party_localvariable", "trp_army_size_troop"),
					(neg|troop_is_hero, ":party_stack_troop_id_main_party_localvariable"),
					(party_stack_get_size, ":party_stack_size_main_party_localvariable", "p_main_party", ":localvariable"),
					(try_begin),
						(gt, ":party_stack_size_main_party_localvariable", 0),
						(store_character_level, ":character_level_party_stack_troop_id_main_party_localvariable", ":party_stack_troop_id_main_party_localvariable"),
						(store_sub, ":value_4", ":character_level_party_stack_troop_id_main_party_localvariable", 10),
						(try_begin),
							(ge, ":character_level_party_stack_troop_id_main_party_localvariable", 25),
							(troop_is_guarantee_horse, ":party_stack_troop_id_main_party_localvariable"),
							(val_mul, ":value_4", 3),
						(try_end),
						(val_add, ":value_11", ":value_4"),
					(try_end),
				(try_end),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party", "p_main_party"),
				(try_begin),
					(le, ":party_size_wo_prisoners_main_party", 300),
					(ge, ":value_11", 2),
					(val_div, ":value_11", 2),
				(try_end),
				(try_begin),
					(is_between, "$contract_fac", "fac_kingdom_1", "fac_kingdoms_end"),
					(eq, "$r_player_class", 0),
					(assign, ":value_11", 0),
				(else_try),
					(is_between, "$contract_fac", "fac_kingdom_1", "fac_kingdoms_end"),
					(ge, ":value_11", 2),
					(val_div, ":value_11", 2),
				(try_end),
				(val_add, ":var_52", ":value_11"),
				(try_begin),
					(gt, "$policy_frugal", 0),
					(le, "$policy_frugal", 5),
					(store_mul, ":value_12", "$policy_frugal", 5),
					(store_sub, ":value_13", 100, ":value_12"),
					(set_show_messages, 0),
					(val_mul, ":var_52", ":value_13"),
					(val_div, ":var_52", 100),
					(set_show_messages, 1),
				(try_end),
				(assign, ":var_61", 0),
				(try_begin),
					(call_script, "script_ship_wage_counting", "$m_ship_type_1"),
					(val_add, ":var_61", "$temp"),
					(call_script, "script_ship_wage_counting", "$m_ship_type_2"),
					(val_add, ":var_61", "$temp"),
					(call_script, "script_ship_wage_counting", "$m_ship_type_3"),
					(val_add, ":var_61", "$temp"),
					(call_script, "script_ship_wage_counting", "$m_ship_type_4"),
					(val_add, ":var_61", "$temp"),
					(call_script, "script_ship_wage_counting", "$m_ship_type_5"),
					(val_add, ":var_61", "$temp"),
				(try_end),
				(try_begin),
					(gt, ":var_61", 3),
					(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party_3", "p_main_party"),
					(lt, ":party_size_wo_prisoners_main_party_3", 200),
					(val_div, ":var_61", 3),
				(try_end),
				(try_begin),
					(eq, "$pirate_king", 1),
					(gt, ":var_61", 3),
					(val_div, ":var_61", 3),
				(try_end),
				(try_begin),
					(gt, "$policy_ship_manage", 0),
					(le, "$policy_ship_manage", 5),
					(store_mul, ":value_12", "$policy_ship_manage", 6),
					(store_sub, ":value_13", 100, ":value_12"),
					(set_show_messages, 0),
					(val_mul, ":var_61", ":value_13"),
					(val_div, ":var_61", 100),
					(set_show_messages, 1),
				(try_end),
				(val_add, ":var_52", ":var_61"),
				(troop_get_slot, ":player_42", "trp_player", 42),
				(try_begin),
					(neq, ":player_42", "p_main_party"),
					(neg|is_between, ":player_42", "p_temp_party", "p_reserved_5"),
					(neq, ":player_42", "p_reserved_5"),
					(party_is_active, ":player_42"),
					(party_slot_eq, ":player_42", slot_party_type, 5),
					(val_add, ":var_52", 500),
				(try_end),
				(troop_get_slot, ":player_42", "trp_player", 43),
				(try_begin),
					(neq, ":player_42", "p_main_party"),
					(neg|is_between, ":player_42", "p_temp_party", "p_reserved_5"),
					(neq, ":player_42", "p_reserved_5"),
					(party_is_active, ":player_42"),
					(party_slot_eq, ":player_42", slot_party_type, 5),
					(val_add, ":var_52", 500),
				(try_end),
				(try_begin),
					(gt, "$workshop_slave", 50),
					(val_add, ":var_52", "$workshop_slave"),
				(try_end),
				(try_begin),
					(call_script, "script_party_money_level_ge", "p_main_party", ":var_52"),
					(neq, "$wm_mo_continue", 1),
					(call_script, "script_party_army_size_execute", "p_main_party", 90, 3),
					(call_script, "script_moral_level_diff", "p_main_party", -10),
					(display_message, "str_nomoney", 0x00ff0000),
				(try_end),
				(display_message, "str_ala_payday", 0x00ffff00),
				(call_script, "script_party_money_level_diff", "p_main_party", ":var_52", 34),
			(try_end),
			(try_begin),
				(gt, "$need_meeting_loose", 0),
				(val_sub, "$need_meeting_loose", 1),
				(display_message, "str_ala_meeting", 0x00ffff00),
			(try_end),
			(try_begin),
				(gt, "$need_meeting_for_ai", 0),
				(le, "$need_meeting_loose", 0),
				(store_random_in_range, ":random_in_range_0_10_2", 0, 10),
				(try_begin),
					(try_begin),
						(eq, "$opinion_suggester", 4),
						(val_add, ":random_in_range_0_10_2", 2),
					(try_end),
					(try_begin),
						(eq, "$need_meeting_for_ai", 11),
						(ge, ":random_in_range_0_10_2", 3),
						(call_script, "script_wm_fac_relation_set", "$wm_player_fac", "$sugester_faction", -10),
						(faction_set_slot, "$wm_player_fac", slot_faction_ai_state, "$declare_war_term"),
					(else_try),
						(ge, ":random_in_range_0_10_2", 3),
						(this_or_next|eq, "$need_meeting_for_ai", 12),
						(eq, "$need_meeting_for_ai", 2),
						(call_script, "script_wm_fac_relation_set", "$wm_player_fac", "$sugester_faction", 10),
					(else_try),
						(ge, ":random_in_range_0_10_2", 5),
						(this_or_next|eq, "$need_meeting_for_ai", 13),
						(eq, "$need_meeting_for_ai", 3),
						(call_script, "script_wm_fac_relation_set", "$wm_player_fac", "$sugester_faction", 30),
					(else_try),
						(ge, ":random_in_range_0_10_2", 5),
						(this_or_next|eq, "$need_meeting_for_ai", 14),
						(eq, "$need_meeting_for_ai", 4),
						(call_script, "script_wm_fac_relation_set", "$wm_player_fac", "$sugester_faction", 90),
					(else_try),
						(eq, "$need_meeting_for_ai", 15),
						(ge, ":random_in_range_0_10_2", 3),
						(call_script, "script_temporary_policy_excute", 1, "$wm_player_fac"),
					(else_try),
						(eq, "$need_meeting_for_ai", 16),
						(ge, ":random_in_range_0_10_2", 3),
						(call_script, "script_temporary_policy_excute", 2, "$wm_player_fac"),
					(else_try),
						(eq, "$need_meeting_for_ai", 17),
						(ge, ":random_in_range_0_10_2", 3),
						(call_script, "script_temporary_policy_excute", 3, "$wm_player_fac"),
					(try_end),
				(try_end),
				(assign, "$need_meeting_for_ai", 0),
				(assign, "$sugester_faction", 0),
				(assign, "$need_meeting_loose", 0),
				(display_message, "str_ala_meet_cancel", 0x00ffff00),
			(try_end),
			(try_begin),
				(gt, "$ruin_qst_target_num", 0),
				(gt, "$ruin_qst_remain_turn", 0),
				(neg|party_slot_ge, "$ruin_qst_target_num", 3, 3),
				(val_sub, "$ruin_qst_remain_turn", 1),
				(assign, reg8, "$ruin_qst_remain_turn"),
				(str_store_party_name, 11, "$ruin_qst_target_num"),
				(store_sub, ":player_player_order_state", "$ruin_qst_target_num", "p_ruin_1"),
				(store_add, ":value_6", "str_r_clue_001", ":player_player_order_state"),
				(str_store_string, 12, ":value_6"),
				(str_store_party_name, 13, "$ruin_qst_giver_loc"),
				(display_message, "str_ruin_quest_mess", 0x00ffffff),
			(else_try),
				(gt, "$ruin_qst_target_num", 0),
				(le, "$ruin_qst_remain_turn", 0),
				(str_store_party_name, 11, "$ruin_qst_giver_loc"),
				(display_message, "str_fail_rep", 0x00ffffff),
			(else_try),
				(gt, "$ruin_qst_target_num", 0),
				(party_slot_ge, "$ruin_qst_target_num", 3, 3),
				(str_store_party_name, 11, "$ruin_qst_giver_loc"),
				(display_message, "str_succ_rep", 0x00ffffff),
			(try_end),
			(assign, "$wm_try_duel", 0),
			(assign, "$wm_steal_try", 0),
			(call_script, "script_rand_glob_dice"),
			(party_set_morale, "p_main_party", 100),
			(try_begin),
				(is_between, "$ply_staying_party_no", "p_pyongyang", "p_place_end"),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party", "p_main_party"),
				(store_faction_of_party, ":faction_of_party_faction_number_of_parties", "$ply_staying_party_no"),
				(store_relation, ":relation_faction_faction_of_party_faction_number_of_parties", "$wm_player_fac", ":faction_of_party_faction_number_of_parties"),
				(this_or_next|lt, ":relation_faction_faction_of_party_faction_number_of_parties", 0),
				(gt, ":party_size_wo_prisoners_main_party", 300),
				(assign, "$ply_staying_party_no", 0),
				(assign, "$ply_staying_army_size", 0),
				(assign, "$ply_staying_army_recruit_on", 0),
				(display_message, "str_t_armystay_disband_enemy", 0x00ff0000),
			(else_try),
				(neg|is_between, "$ply_staying_party_no", "p_pyongyang", "p_place_end"),
				(assign, "$ply_staying_party_no", 0),
				(assign, "$ply_staying_army_size", 0),
				(assign, "$ply_staying_army_recruit_on", 0),
			(try_end),
			(call_script, "script_init_main_party_core_slot"),
			(call_script, "script_paohu_r18_control")
		]),

]